General fixes and Printf Fix
HyperloopUPV-H8/ST-LIB pull request #123
Opened 2022-12-21 21:17 UTC by PabloGonzalezSegarra

### General fixes

- Added TIM guard in StateMachine
- Moved som code from .hpp to .cpp to avoid weird bugs

### Printf 

Se han arreglado los `printf` y simplicado su uso. Ahora forman parte del servicio de UART y se puede ver como utilizarlos a continuación.

```cpp
  UART::set_up_printf(UART::uart3);
  UART::start();

  printf("123456789%s", endl);
  fprintf(stderr, "Error xD!%s", endl);
```

Ya no hace falta configurar nada para hacerlos funcionar, por tanto el articulo sobre los printf ha quedado desactualizado. Se modificará lo antes posible.

2022-12-22 10:53 UTC, alejandrogonzalvo requested changes
En general bien, mira los refactors

2022-12-22 10:53 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/UART/UART.hpp
> +    static uint8_t printf_uart;
```suggestion
    };

public:
    static uint16_t id_counter;
    
    static unordered_map<uint8_t, UART::Instance* > registered_uart;
    static unordered_map<UART::Peripheral, UART::Instance*> available_uarts;

    static uint8_t printf_uart;
```

2022-12-22 10:53 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +bool UART::transmit(uint8_t id, uint8_t data){
```suggestion
bool UART::transmit(uint8_t id, uint8_t data){
    UART::transmit(id, &data, 1);
}
```
Si esto compila, en vez de copiar y pegar la funcion dos veces puedes llamar a la funcion general en el caso especifico

2022-12-22 10:53 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
>      UART::Instance* uart = UART::registered_uart[id];
```suggestion
    UART::UART_HandleTypeDef* handle = UART::registered_uart[id]->huart;
```
Creo que en esta funcion solo usas el handle, por lo que puedes asignarlo directamente y todos los
`uart->huart->variable` quedan `handle->variable`. Ya que estas podrias cambiarle el nombre de la variable huart de instance a handle, a mi me gusta mas personalmente como veas.

2022-12-22 10:53 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +		if(!id.has_value()){
```suggestion
		if(not id){
```
Creo que el has_value es redundante

2022-12-22 11:12 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +		if(!id.has_value()){
A mi me gusta más poner el has_value pero me da igual.

2022-12-24 19:41 UTC, StefanCostea approved these changes

2022-12-24 19:41 UTC, StefanCostea commented on Inc/HALAL/Services/Communication/UART/UART.hpp
> +    static void print_by_uart(char *ptr, int len);
why arent you using string?

2022-12-24 19:44 UTC, alejandrogonzalvo requested changes

2022-12-24 19:44 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/UART/UART.hpp
> +    static bool transmit(uint8_t id, uint8_t* data, int16_t size);
```suggestion
    static bool transmit(uint8_t id, array data);
```
Si vas a cambiarlo en el SPI cambialo tambien en el UART. Es hacer data.size() y data.data(), no hace falta que cambies nada de la funcion.

2022-12-27 16:46 UTC, Dgoncas approved these changes

2022-12-27 17:38 UTC, alejandrogonzalvo approved these changes

2022-12-27 17:38 UTC, merged