update UART to use spans
HyperloopUPV-H8/ST-LIB pull request #138
Opened 2023-01-11 19:21 UTC by alejandrogonzalvo

# NEW UART 📡 

This PR fixes UART and updates the implementation to use Spans.

## Usage: 👨‍💻

2023-01-11 19:24 UTC, ricardochust approved these changes

2023-01-11 20:13 UTC, StefanCostea approved these changes

2023-01-12 18:32 UTC, PabloGonzalezSegarra requested changes
Arregla el doxygen y lo apruebo.

2023-01-14 09:13 UTC, PabloGonzalezSegarra approved these changes

2023-01-14 09:29 UTC, merged