ST-LIB Start
HyperloopUPV-H8/ST-LIB pull request #140
Opened 2023-01-12 08:49 UTC by alejandrogonzalvo

# ST-LIB Start 🚀 
This PR implements the ST-LIB start, so you don't have to worry about the order of the peripherals initialization anymore.

## Before

```cpp
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

int main(void)
{
  HAL_Init();
  SystemClock_Config();
  PeriphCommonClock_Config();

  uint8_t spi_instance = SPI::inscribe(SPI::spi3).value_or(69);

  Pin::start();
  SPI::start();
```

## After
```cpp
int main(void)
{
  HAL_Init();
  
  uint8_t spi_instance = SPI::inscribe(SPI::spi3).value_or(69);

  ST-LIB::start();
```
## TODO:

- All testing.
- Add ifdefs around starts.

2023-01-21 14:06 UTC, PabloGonzalezSegarra commented on Src/HALAL/HALAL.cpp
> +	//Ethernet::start(local_ip, subnet_mask, gateway);
Las IP deberian ser unos defines en las RUNES asi se pueden cambiar para cada placa.

2023-01-21 14:06 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/HALconfig/Halconfig.cpp
> +void HALconfig::system_clock() {
Este reloj es el que usan las placas o las nucleos?

2023-01-21 20:30 UTC, StefanCostea commented on Src/HALAL/HALAL.cpp
> +	//Ethernet::start(local_ip, subnet_mask, gateway);
buena idea

2023-01-22 03:48 UTC, StefanCostea requested changes

2023-01-22 08:41 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/HALconfig/Halconfig.cpp
> +void HALconfig::system_clock() {
Aqui quizas podriamos tener un define que sea 
```cpp
#define PLATFORM NUCLEO //BOARD
```
y que cambie las cosas necesarias para que funcione el mismo proyecto en una nucelo o en una placa.

2023-01-22 11:10 UTC, StefanCostea commented on Src/HALAL/Models/HALconfig/Halconfig.cpp
> +void HALconfig::system_clock() {
tambien es cierto,deberiamos recopilar todas las cosas para que el codigo funcione indiferente en ambas cambiando un define

2023-01-22 16:11 UTC, alejandrogonzalvo commented on Src/HALAL/Models/HALconfig/Halconfig.cpp
> +void HALconfig::system_clock() {
Pasadme la configuracion del reloj por Slack y la pongo con los defines

2023-01-22 16:19 UTC, alejandrogonzalvo commented on Src/HALAL/HALAL.cpp
> +	//Ethernet::start(local_ip, subnet_mask, gateway);
mas que unos defines, yo pondria en el eth unas variables privadas estáticas con un valor por defecto.

2023-01-22 18:27 UTC, StefanCostea commented on Src/HALAL/HALAL.cpp
> +	//Ethernet::start(local_ip, subnet_mask, gateway);
unas constexpr de la clase IPV4

2023-01-25 20:00 UTC, StefanCostea commented
![](https://github.trello.services/images/mini-trello-icon.png) [STLIB Init](https://trello.com/c/0KA9BSiY/57-stlib-init)

2023-01-26 10:50 UTC, Dgoncas approved these changes

2023-01-29 17:19 UTC, PabloGonzalezSegarra commented on Src/HALAL/HALAL.cpp
> +	if (HAL_CORDIC_Init(&hcordic) != HAL_OK){}
Añade el errorhandler

2023-01-29 17:19 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/HALconfig/Halconfig.cpp
> +void HALconfig::system_clock() {
Esta configuración tiene en cuenta los últimos cambios para el FDCAN?

2023-01-30 18:11 UTC, PabloGonzalezSegarra requested changes
¿Esto es lo que hiciste para que te funcionase cuando estabas rayado? Igual no compila por esto.

2023-02-01 20:12 UTC, StefanCostea approved these changes

2023-02-01 20:13 UTC, StefanCostea approved these changes

2023-02-01 20:14 UTC, merged