[DON T MERGE] math+cordic bug solving
HyperloopUPV-H8/ST-LIB pull request #142
Opened 2023-01-13 17:23 UTC by ricardochust

### Bugs solved:

the tangent did a division by 0 on some arbitrary numbers that were out of the safe guard. Now it s tested for every possible bit value and it does not divide by 0 (and the sample results were as precise as expected)

module 

### Bugs known (not solved):

using at max speed multiple different math functions without anything in between may cause the configuration to not be correctly applied and some of the results being aberrant. To be exact seems that cosine, sine, and tangent are affected. Maybe changing the CORDIC code to a single shot structure (math does only single shot anyway) could solve the issue.

2023-01-14 11:17 UTC, alejandrogonzalvo requested changes
Cuando cambies los punteros por un array, tendras que pasarle la direccion al CORDIC para que siga funcionando. De momento eso para este PR puede estar bien, pero creo que en el futuro tiene mas sentido hacer este cambio en el codigo del Cordic para no pasarle la direccion:

### Before
```cpp
void RotationComputer::cos(int32_t *angle, int32_t *out, int32_t size){
	if(RotationComputer::mode != COSINE){
		RotationComputer::mode = COSINE;
		MODIFY_REG(CORDIC -> CSR,
					RESET_MASK,
					COSINE_CONFIG
		);
	}
	for(int n = 0; n < size; n++){
		CORDIC -> WDATA = angle[n];
		out[n] = CORDIC -> RDATA;
	}
}
```

### After
```cpp
void RotationComputer::cos(span<int32_t> angle, span<int32_t> out){
	if(RotationComputer::mode != COSINE){
		RotationComputer::mode = COSINE;
		MODIFY_REG(CORDIC -> CSR,
					RESET_MASK,
					COSINE_CONFIG
		);
	}

	for(int n : angle.size()){
		CORDIC -> WDATA = angle[n];
		out[n] = CORDIC -> RDATA;
	}
}
```
Le quitas un argumento a la funcion, y te aseguras que no se te va out of bounds ya que de eso se encarga el span (una responsabilidad menos para el programador, mas seguro).

Si quieres un dia lo vemos en Malva y lo testeamos en otro PR.

2023-01-14 19:33 UTC, ricardochust commented on Inc/ST-LIB_LOW/Math/Math.hpp
> +    static int32_t *pointer4;
done

2023-01-14 19:44 UTC, ricardochust commented
> Cuando cambies los punteros por un array, tendras que pasarle la direccion al CORDIC para que siga funcionando. De momento eso para este PR puede estar bien, pero creo que en el futuro tiene mas sentido hacer este cambio en el codigo del Cordic para no pasarle la direccion:
> 
> ### Before
> ```c++
> void RotationComputer::cos(int32_t *angle, int32_t *out, int32_t size){
> 	if(RotationComputer::mode != COSINE){
> 		RotationComputer::mode = COSINE;
> 		MODIFY_REG(CORDIC -> CSR,
> 					RESET_MASK,
> 					COSINE_CONFIG
> 		);
> 	}
> 	for(int n = 0; n < size; n++){
> 		CORDIC -> WDATA = angle[n];
> 		out[n] = CORDIC -> RDATA;
> 	}
> }
> ```
> 
> ### After
> ```c++
> void RotationComputer::cos(span<int32_t> angle, span<int32_t> out){
> 	if(RotationComputer::mode != COSINE){
> 		RotationComputer::mode = COSINE;
> 		MODIFY_REG(CORDIC -> CSR,
> 					RESET_MASK,
> 					COSINE_CONFIG
> 		);
> 	}
> 
> 	for(int n : angle.size()){
> 		CORDIC -> WDATA = angle[n];
> 		out[n] = CORDIC -> RDATA;
> 	}
> }
> ```
> 
> Le quitas un argumento a la funcion, y te aseguras que no se te va out of bounds ya que de eso se encarga el span (una responsabilidad menos para el programador, mas seguro).
> 
> Si quieres un dia lo vemos en Malva y lo testeamos en otro PR.

El problema es sobretodo para la cohesion de los returns. 

Algunos metodos devuelven un solo valor y los otros devuelven dos. Las opciones serian:
devolver los de un solo valor como una int32_t y los de dos valores como una tupla/array
devolver ambos como una tupla/array
recibir un puntero donde guardarlos y guardarlos en estos (lo que se hace ahora)

Luego eso seria para un supuesto metodo single shot, porque para los que reciban mas de un valor (que es la mejor forma de aprovechar el cordic, enviarle varias peticiones de la misma operacion, y para lo que estan preparado los de ahora) deberian devolver una array/vector o una tupla de arrays/vector, que lo considero algo mas engorrosos de manipular que decirle tu donde lo guarda y punto (se podria hacer pero habria que hablarlo para que tuviese algo de cohesion)

2023-01-15 11:24 UTC, alejandrogonzalvo approved these changes
Aproved, pero mira los dos comentarios

2023-01-15 11:24 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Math/Math.cpp
> +array<int32_t, 4> Math::pointers = {0,0,0,0};
```suggestion
array<int32_t, 4> Math::pointers = { 0 };
```

Esto inicializa todo a cero. Es mejor porque es independiente del tamaño del array, si lo cambiaras no tienes que añadir o quitar ceros. Tambien es mas limpio

2023-01-15 11:24 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Math/Math.cpp
> +    return pointers[2] / (pointers[1] >> TG_DECIMAL_BITS);
Mamon lo has marcado como resuelto y lo has dejado igual, por lo menos dime porque no lo cambias si hay algun motivo XD

2023-01-15 12:01 UTC, ricardochust commented on Src/ST-LIB_LOW/Math/Math.cpp
> +    return pointers[2] / (pointers[1] >> TG_DECIMAL_BITS);
ha sido un pedo cerebral, pense que era el mismo problema que el comentario de arriba por alguna razón.

Si, no hay problema con ponerlo así, aunque me perturba un poco que no sea el return de fuera el bueno, por eso de que el estandar es poner primero los ifs que handlean el caso de error, y luego cuando ya pasas todas las condiciones haces la operacion para la que el metodo estaba destinado.

2023-01-18 10:53 UTC, ricardochust commented on Src/ST-LIB_LOW/Math/Math.cpp
> +    return pointers[2] / (pointers[1] >> TG_DECIMAL_BITS);
donete

2023-01-21 13:58 UTC, PabloGonzalezSegarra approved these changes

2023-01-21 21:17 UTC, StefanCostea approved these changes

2023-01-22 03:50 UTC, merged