Features/error handler
HyperloopUPV-H8/ST-LIB pull request #143
Opened 2023-01-14 09:12 UTC by PabloGonzalezSegarra

# Module description
The ErrorHandler is a class that handles code implementation errors. It will be in charge of triggering a protection that will set to fault the vehicle and send the error message via UART and in the future also via Ethernet.

# Minimal configuration
Below you can see the minimum configuration to make the ErrorHandler work:

```cpp
int main(void)
{
  HAL_Init();
  SystemClock_Config();
  PeriphCommonClock_Config();

  //Configuramos los printf por uart para ver el mensaje de error
  UART::set_up_printf(UART::uart2);

  //Añadimos la protección del ErrorHandler para que el vehiculo entre en fault si salta el ErrorHandler
  ProtectionManager_add_protection(&ErrorHandlerModel::error_triggered, ProtectionType::NOT_EQUALS, 0);

  //Inicializamos los servicios necesarios de la HALAL
  Pin::start();
  UART::start();
  Time::start();

  uint8_t a = 21;
  //Hacemos saltar el ErrorHandler con un mensaje.
  ErrorHandlerModel::ErrorHandler("A problem occurred during UART inscribe, UART number: %d", a);

  while (1) {
	  ErrorHandlerModel::ErrorHandlerUpdate();
  }

}

```
NOTE: Although it is not shown in the code because it does not concern this pull request, the protection manager needs more configuration to work, in addition to calling update.

The resulting message will be the following:
![image](https://user-images.githubusercontent.com/58437819/212464707-272fd707-83cf-4735-b11e-38375c5631d4.png)

# Tests

The code shown above has been tested in addition to many other tests with all kinds of messages and variables, verifying that the ErrorHandler always jumps even if the formatting fails because it is specified incorrectly.

2023-01-14 10:29 UTC, alejandrogonzalvo requested changes

2023-01-14 10:29 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
> +
```suggestion

using std::snprintf;
using std::make_unique;
using std::string;

```
Mas limpio poner en el hpp lo que vas a gastar y no poner std:: en las implementaciones, pienso que deberia ser el convenio para la libreria

2023-01-14 10:29 UTC, alejandrogonzalvo commented on Inc/C++Utilities/CppUtils.hpp
> -namespace chrono = std::chrono;
Porque borras esto? A mi no me compilaba sin esto

2023-01-21 12:23 UTC, alejandrogonzalvo submitted a review, later dismissed

2023-01-21 12:23 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
> +#define ErrorHandler(x, args...) do { ErrorHandlerModel::GetMetaData(__LINE__, __FUNCTION__, __FILE__); \
No era mas facil que fuera un namespace?

2023-01-21 12:23 UTC, alejandrogonzalvo commented on Src/HALAL/Models/Packets/Packet.cpp
> +map<decltype(Packet<>::id), function<void(uint8_t*)>> Packet<>::save_by_id = {};
```suggestion
map<uint16_t, function<void(uint8_t*)>> Packet<>::save_by_id = {};
```

2023-01-21 12:23 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +		UART::print_by_uart(retorno, 1);
No seria len 2 porque es \n \r

2023-01-21 12:23 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
> +		ErrorHandlerModel::file = std::string(file);
```suggestion
		ErrorHandlerModel::file = string(file);
```

O ponemos std en todo, o en nada. Creo que mejor en nada, añade los using al hpp

2023-01-21 13:38 UTC, PabloGonzalezSegarra commented on Inc/C++Utilities/CppUtils.hpp
> -namespace chrono = std::chrono;
tienes razon, fallo mio

2023-01-21 13:38 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
> +
Listo

2023-01-21 13:40 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
> +#define ErrorHandler(x, args...) do { ErrorHandlerModel::GetMetaData(__LINE__, __FUNCTION__, __FILE__); \
Yo lo veo más clean asi

2023-01-21 13:50 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +		UART::print_by_uart(retorno, 1);
Nope, porque el \n se imprime en el print anterior y el \r se imprime en el siguiente.

2023-01-21 13:52 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/Packets/Packet.cpp
> +map<decltype(Packet<>::id), function<void(uint8_t*)>> Packet<>::save_by_id = {};
El código de la clase packet no lo toco, solo lo he puesto en un .cpp porque si no no compilaba la ST-LIB

2023-01-21 16:28 UTC, ricardochust approved these changes
Asumire que has comprobado que todo funciona al eliminar las 6 lineas de PacketValue.hpp

2023-01-21 18:39 UTC, alejandrogonzalvo approved these changes

2023-01-21 20:29 UTC, StefanCostea requested changes

2023-01-21 20:29 UTC, StefanCostea commented on Middlewares/Third_Party/LwIP/src/include/lwip/opt.h
> +#define DHCP_DEBUG                      LWIP_DBG_ON
quita eso

2023-01-21 20:29 UTC, StefanCostea commented on Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
> +#ifdef LED_FAULT
quita esto tb

2023-01-21 21:05 UTC, StefanCostea approved these changes

2023-01-21 21:06 UTC, merged