ready for run tests
HyperloopUPV-H8/ST-LIB pull request #158
Opened 2023-01-22 23:53 UTC by PabloGonzalezSegarra

# FDCAN SERVICE

EL serivicio de FDCAN funciona exactamente igual que el resto de servicios con la excepción que en el recibo del mensaje los mensajes se guardan en una cola y el usuario accede a los mensajes que han llegado a traves de esta cola.

# Tests

!Faltan por pasar todos los tests necesarios ¡

2023-01-23 10:05 UTC, alejandrogonzalvo requested changes

2023-01-23 10:05 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
> +	handle->Init.TxElmtSize = FDCAN_DATA_BYTES_8;
```suggestion
	FDCAN_HandleTypeDef* handle = fdcan->hfdcan;
	tipo_init_lo_que_sea& init_data = handle->init;
	
	init_data.FrameFormat = FDCAN_FRAME_FD_BRS;
	init_data.Mode = FDCAN_MODE_NORMAL;
	init_data.AutoRetransmission = ENABLE;
	init_data.TransmitPause = DISABLE;
	init_data.ProtocolException = DISABLE;
	init_data.NominalPrescaler = 16;
	init_data.NominalSyncJumpWidth = 0x10;
	init_data.NominalTimeSeg1 = 0x3F;
	init_data.NominalTimeSeg2 = 0x10;
	init_data.DataPrescaler = 1;
	init_data.DataSyncJumpWidth = 0x4;
	init_data.DataTimeSeg1 = 0xF;
	init_data.DataTimeSeg2 = 0x4;
	init_data.MessageRAMOffset = 0;
	init_data.StdFiltersNbr = 1;
	init_data.ExtFiltersNbr = 0;
	init_data.RxFifo0ElmtsNbr = 0;
	init_data.RxFifo0ElmtSize = FDCAN_DATA_BYTES_8;
	init_data.RxFifo1ElmtsNbr = 0;
	init_data.RxFifo1ElmtSize = FDCAN_DATA_BYTES_8;
	init_data.RxBuffersNbr = 0;
	init_data.RxBufferSize = FDCAN_DATA_BYTES_8;
	init_data.TxEventsNbr = 0;
	init_data.TxBuffersNbr = 0;
	init_data.TxFifoQueueElmtsNbr = 0;
	init_data.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
	init_data.TxElmtSize = FDCAN_DATA_BYTES_8;
```

2023-01-24 04:52 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
> +	return id;
Que aporta esto?

2023-01-24 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
> +	return id;
no declaras una variable, es un refactor. Si no te gusta, asignalo por referencia al menos no lo copies.

2023-01-24 17:37 UTC, StefanCostea approved these changes

2023-01-24 17:48 UTC, alejandrogonzalvo requested changes

2023-01-24 17:48 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
> +		ErrorHandler("El fdcan %d no es un fdcan válido.", fdcan);
Los comentarios en ingles todos, cambialos.
```suggestion
		ErrorHandler("FDCAN %d is not a valid instance.", fdcan);
```

2023-01-25 11:12 UTC, alejandrogonzalvo submitted a review, later dismissed

2023-01-25 19:42 UTC, StefanCostea approved these changes

2023-01-25 19:59 UTC, StefanCostea commented
![](https://github.trello.services/images/mini-trello-icon.png) [FDCAN Service](https://trello.com/c/gvAU7VVM/92-fdcan-service)

2023-01-26 10:37 UTC, Dgoncas approved these changes

2023-01-26 13:53 UTC, alejandrogonzalvo approved these changes

2023-01-26 13:54 UTC, merged