Added to_string method to Pin
HyperloopUPV-H8/ST-LIB pull request #166
Opened 2023-01-25 18:07 UTC by StefanCostea

Added to_string method to Pin

2023-01-25 20:00 UTC, StefanCostea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Añadir to_String a Pin](https://trello.com/c/xIoCRHSK/93-a%C3%B1adir-tostring-a-pin)

2023-01-25 21:22 UTC, ricardochust approved these changes

2023-01-26 08:11 UTC, PabloGonzalezSegarra requested changes

2023-01-26 08:11 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/PinModel/Pin.cpp
> +map<Pin,string> Pin::map_to_string = {
Hazlo constante.

2023-01-26 10:06 UTC, alejandrogonzalvo approved these changes

2023-01-26 10:15 UTC, Dgoncas approved these changes

2023-01-26 13:43 UTC, alejandrogonzalvo approved these changes

2023-01-26 13:46 UTC, PabloGonzalezSegarra requested changes
Primero el puerto.

2023-01-26 13:48 UTC, PabloGonzalezSegarra approved these changes

2023-01-26 13:49 UTC, merged