Encoder Fix
HyperloopUPV-H8/ST-LIB pull request #174
Opened 2023-01-27 23:06 UTC by PabloGonzalezSegarra

Se han solucionado varios bugs que habian en el EncoderSensor

2023-01-28 08:15 UTC, alejandrogonzalvo requested changes

2023-01-28 08:15 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	EncoderSensor(Pin pin1, Pin pin2, double* position, double* direction, double* speed, double* acceleration);
```suggestion
	EncoderSensor(Pin& pin1, Pin& pin2, double* position, double* direction, double* speed, double* acceleration);
```

Pines por referencia

2023-01-28 08:15 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
>  	}
```suggestion
	if(clock_time < last_clock_time) {
		handle_overflow();
	}
```
All my homies hate comments. Ahora en serio, asi te ahorras el comentario, y maskeas la operacion, por si alguien quiere revisar la logica y no le interesa el calculo

2023-01-28 08:15 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
>  	*acceleration = (delta_speed) / (delta_time);
```suggestion
	*acceleration = delta_speed / delta_time;
```
No son necesarios no?

2023-01-28 08:15 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
>  	*speed = abs(delta_position) / (delta_time);
```suggestion
	*speed = abs(delta_position) / delta_time;
```

2023-01-28 08:16 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
>  	}
haces una funcion privada

2023-01-28 12:32 UTC, StefanCostea approved these changes

2023-01-28 18:22 UTC, PabloGonzalezSegarra commented
Todos estos cambios son para válidación, esta clase ya fue aprobada y no voy a cambiar nada que no sean bugs. Los cambios de optimización y limpieza de código los haremos en el proxima sprint. Marcad todos los fallos como issues y se los arreglamos cuando toque.

2023-01-29 18:56 UTC, alejandrogonzalvo approved these changes

2023-01-30 18:44 UTC, ricardochust approved these changes

2023-01-30 18:46 UTC, merged