Fix/spi error handler
HyperloopUPV-H8/ST-LIB pull request #198
Opened 2023-02-02 18:52 UTC by PabloGonzalezSegarra

2023-02-02 19:03 UTC, StefanCostea requested changes

2023-02-02 19:03 UTC, StefanCostea commented on Src/HALAL/Services/Communication/SPI/SPI.cpp
> -		return nullopt; //TODO: Error handler or throw the exception
esto no hace error handler?

2023-02-03 08:53 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/SPI/SPI.cpp
> -		return nullopt; //TODO: Error handler or throw the exception
No, quedamos que el inscribe se manejaria desde fuera.

2023-02-03 14:59 UTC, alejandrogonzalvo approved these changes

2023-02-06 07:50 UTC, StefanCostea approved these changes

2023-02-06 16:26 UTC, ricardochust approved these changes

2023-02-07 13:49 UTC, merged

2023-02-10 15:22 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/SPI/SPI.cpp
> -		return nullopt; //TODO: Error handler or throw the exception
What is this