fix todos
HyperloopUPV-H8/ST-LIB pull request #199
Opened 2023-02-02 18:57 UTC by alejandrogonzalvo

2023-02-02 18:59 UTC, StefanCostea requested changes

2023-02-02 18:59 UTC, StefanCostea commented on Src/ST-LIB_HIGH/Protections/Protection.cpp
> +    	printf("You can not use two values for this protection");
porque un printf y no un errorhandler?

2023-02-04 17:52 UTC, PabloGonzalezSegarra requested changes

2023-02-04 17:52 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/LowPowerTimer/LowPowerTimer.cpp
> +	  ErrorHandler("The LPTIM %s could not be registered", name);
De donde sacas la variable name?

2023-02-06 07:52 UTC, StefanCostea commented on Src/HALAL/Models/LowPowerTimer/LowPowerTimer.cpp
> +	  ErrorHandler("The LPTIM %s could not be registered", name);
del contructor

2023-02-06 07:52 UTC, StefanCostea approved these changes

2023-02-06 14:02 UTC, PabloGonzalezSegarra approved these changes

2023-02-06 16:25 UTC, ricardochust approved these changes

2023-02-07 13:48 UTC, merged