Fix/falling trigger
HyperloopUPV-H8/ST-LIB pull request #205
Opened 2023-02-08 08:59 UTC by alejandrogonzalvo

This PR enables to register EXTI interruption as rising or falling edge.

2023-02-08 09:18 UTC, PabloGonzalezSegarra approved these changes
Suponiendo, con poca fe, que has hecho los tests necesarios esta bien.

2023-02-08 16:12 UTC, ricardochust approved these changes

2023-02-08 18:09 UTC, StefanCostea requested changes

2023-02-08 18:09 UTC, StefanCostea commented on Src/HALAL/Services/EXTI/EXTI.cpp
> +optional<uint8_t> ExternalInterrupt::inscribe(Pin& pin, function<void()>&& action, TRIGGER trigger) {
pon un trigger por defecto rising

2023-02-10 09:35 UTC, alejandrogonzalvo commented on Src/HALAL/Services/EXTI/EXTI.cpp
> +optional<uint8_t> ExternalInterrupt::inscribe(Pin& pin, function<void()>&& action, TRIGGER trigger) {
Esta puesto, solo se pone en el hpp.

2023-02-10 14:35 UTC, ricardochust approved these changes

2023-02-14 15:16 UTC, merged