Features/i2 c service
HyperloopUPV-H8/ST-LIB pull request #210
Opened 2023-02-10 21:51 UTC by ricardochust

2023-02-12 11:50 UTC, alejandrogonzalvo requested changes
Revisar también toda la identación

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        uint32_t speed_frequency = 100; /**< frequency in khz*/
```suggestion
        uint32_t speed_frequency_in_khz = 100;
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        uint32_t data_length = 8; /**< size in bits*/
```suggestion
        uint32_t data_length_in_bits = 8; 
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        bool receive_ready = false; /**< Receive value is ready to use pin. */
```suggestion
        bool is_receive_ready = false; /**< Receive value is ready to use pin. */
```
no entiendo el comentario, que significa el pin?

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        bool initialized = false;
```suggestion
        bool is_initialized = false;
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +    static I2C::Peripheral i2c2;
```suggestion
    static I2C::Peripheral i2c2;
```
esto no deberia ir en runes?

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +    static bool transmit_next_packet(uint8_t id, I2CPacket& packet);
```suggestion
    static bool transmit(uint8_t id, I2CPacket& packet);
```
Que aporta next_packet?

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +    static bool receive_next_packet(uint8_t id, I2CPacket& packet);
```suggestion
    static bool receive(uint8_t id, I2CPacket& packet);
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +     * @brief This method is used to check if the UART receive operation has finished and data is ready.
Estos coments pone UART y es I2C. Si se documenta, hay que actualizarlo

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +		return nullopt; //TODO: Error handler or throw the exception
```suggestion
		return nullopt;
```
en los inscribes quedamos que el error se propaga

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +		I2C::init(iter.second);
```suggestion
	for(auto  [id, instance] : I2C::active_i2c){
		I2C::init(instance);
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +        return false; //TODO: Error handler
```suggestion
        return false; //TODO: Error handler
```
Añadir Error Handler

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +    	ErrorHandler("Error during I2C transmission\n\r");
```suggestion
    	ErrorHandler("Error during I2C Master Transmit DMA\n\r");
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +    printf("Packet send successfully \n\r");
```suggestion
    printf("Packet send successfully \n\r");
```
Los prints son solo para debug, no se ponen en la libreria

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +void HAL_I2C_MasterRxCpltCallback(I2C_HandleTypeDef * hi2c){
```suggestion
void HAL_I2C_MasterRxCpltCallback(I2C_HandleTypeDef *hi2c){
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +		 printf("I2C Error during receive!\n\r");
```suggestion
		 printf("I2C Error during memory read DMA!\n\r");
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +	i2c->hi2c->Init.Timing = 0x60404E72;
```suggestion
	InitDataType& init_data = i2c->hi2c->Init;
	
	init_data.Timing = 0x60404E72;
```

2023-02-12 11:50 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +		ErrorHandler("Error configurating Analog Filter of the I2C");
```suggestion
		ErrorHandler("Error configurating Analog Filter of the I2C");
```
Lo mismo que los errores de arriba. Cada error ha de ser concreto, informativo y unico

2023-02-13 10:22 UTC, ricardochust commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        uint32_t speed_frequency = 100; /**< frequency in khz*/
done

2023-02-13 10:23 UTC, ricardochust commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        uint32_t data_length = 8; /**< size in bits*/
done

2023-02-13 10:24 UTC, ricardochust commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        bool receive_ready = false; /**< Receive value is ready to use pin. */
done

2023-02-13 10:25 UTC, ricardochust commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +        bool initialized = false;
done

2023-02-13 10:26 UTC, ricardochust commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +    static I2C::Peripheral i2c2;
no te voy a mentir, me he copiado del uart. En el uart se declara en el hpp de la clase y se inicializa en el runes. Si quieres lo cambio pero entonces habria que cambiarlo tambien en el uart imagino

2023-02-13 10:28 UTC, ricardochust commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +    printf("Packet send successfully \n\r");
tengo que acordarme de borrarlo cuando termine de debuggear, me dejo esta abierta

2023-02-13 10:28 UTC, ricardochust commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +void HAL_I2C_MasterRxCpltCallback(I2C_HandleTypeDef * hi2c){
done

2023-02-13 10:33 UTC, ricardochust commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +		 printf("I2C Error during receive!\n\r");
done

2023-02-13 10:34 UTC, ricardochust commented on Src/HALAL/Services/Communication/I2C/I2C.cpp
> +	i2c->hi2c->Init.Timing = 0x60404E72;
eso da un warning, por eso no lo hice. Si os da igual el warning lo hago, pero se queja de que no lo uso.

2023-02-24 09:53 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Communication/I2C/I2C.hpp
> +    static I2C::Peripheral i2c2;
ok, cierro

2023-03-31 13:34 UTC, hyperloop-orangeman commented
hola

2023-03-31 13:35 UTC, hyperloop-orangeman commented
hola

2023-03-31 13:35 UTC, hyperloop-orangeman commented
hola

2023-03-31 13:43 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 2023-03-31-13-42-07

2023-03-31 13:46 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 2023-03-31-13-46-32; Ultima modificacion del PR: 2023-03-31-13-46-07

2023-03-31 13:48 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:48:09 de 31/03/2023; Ultima modificacion del PR: 13:46:33 de 31/03/2023

2023-03-31 13:51 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:51:06 de 31/03/2023; Ultima modificacion del PR: 13:48:10 de 31/03/2023

2023-03-31 13:52 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:52:53 de 31/03/2023; Ultima modificacion del PR: 13:51:07 de 31/03/2023

2023-03-31 13:54 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:54:28 de 31/03/2023; Ultima modificacion del PR: 13:52:53 de 31/03/2023

2023-03-31 13:54 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:54:47 de 31/03/2023; Ultima modificacion del PR: 13:54:28 de 31/03/2023

2023-03-31 13:57 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:57:01 de 31/03/2023; Ultima modificacion del PR: 13:56:10 de 31/03/2023

2023-03-31 14:22 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:22:06 de 31/03/2023; Ultima modificacion del PR: 14:21:14 de 31/03/2023

2023-03-31 14:22 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:22:21 de 31/03/2023; Ultima modificacion del PR: 14:22:07 de 31/03/2023

2023-03-31 14:36 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:36:12 de 31/03/2023; Ultima modificacion del PR: 14:22:22 de 31/03/2023

2023-03-31 14:37 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:37:00 de 31/03/2023; Ultima modificacion del PR: 14:36:13 de 31/03/2023

2023-03-31 14:37 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:37:26 de 31/03/2023; Ultima modificacion del PR: 14:37:00 de 31/03/2023

2023-03-31 14:37 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:37:39 de 31/03/2023; Ultima modificacion del PR: 14:37:27 de 31/03/2023

2023-03-31 14:39 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:39:13 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 14:39 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:39:27 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 14:43 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:43:01 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 14:48 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:48:54 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 15:13 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:13:26 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 15:29 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:29:03 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 15:32 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:32:16 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 15:56 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:56:40 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 15:58 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:58:46 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:02 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:02:40 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:03 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:03:10 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:03 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:03:32 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:07 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:07:07 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:09 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:09:26 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:14 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:14:38 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:16 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:16:41 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:21 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:21:30 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:35 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:35:33 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:36 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:36:38 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 16:50 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:50:26 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-03-31 17:10 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 19:10:39 de 31/03/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-04-04 13:22 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:22:42 de 04/04/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-04-04 13:33 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:33:26 de 04/04/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-04-04 13:34 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:34:55 de 04/04/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-04-04 13:39 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:39:44 de 04/04/2023; Ultima modificacion del PR: 3e9b582bbdb86ba7b6326a5e2e02055aab0f8da6

2023-04-06 13:23 UTC, ricardochust commented
i2c polling working (tested with TCU Sensors and Analog Discovery)

2023-04-17 14:18 UTC, merged