Nested state machines
HyperloopUPV-H8/ST-LIB pull request #213
Opened 2023-02-21 16:59 UTC by alejandrogonzalvo

Testcase:
```cpp
#include "main.h"
#include "lwip.h"

#include "ST-LIB.hpp"
#include "Runes/Runes.hpp"
#include "Examples/examples_includes.hpp"

using namespace std::chrono_literals;

extern struct netif gnetif;

int main(void)
{
	uint8_t state1 = 0;
	uint8_t state2 = 1;
	uint8_t state2_1 = 2;
	uint8_t state2_2 = 3;
	uint8_t state2_3 = 4;

	StateMachine general_sm(state1);
	general_sm.add_state(state2);

	StateMachine specific_sm(state2_1);
	specific_sm.add_state(state2_2);
	specific_sm.add_state(state2_3);

	int contador = 0;

	STLIB::start(Nucleo);

	printf("Iniciando Testcase State Machine:\n");

	general_sm.add_cyclic_action([&](){
		printf("Estado 1\n");
	}, 100ms, state1);

	specific_sm.add_cyclic_action([&](){
		printf("Estado 2.1\n");
	}, 100ms, state2_1);

	specific_sm.add_cyclic_action([&](){
		printf("Estado 2.2\n");
	}, 100ms, state2_2);

	specific_sm.add_cyclic_action([&](){
		printf("Estado 2.3\n");
	}, 100ms, state2_3);

	specific_sm.add_transition(state2_1, state2_2, [](){ return true; });
	specific_sm.add_transition(state2_2, state2_3, [](){ return true; });
	specific_sm.add_transition(state2_3, state2_1, [](){ return true; });

	general_sm.add_state_machine(&specific_sm, state2);

	general_sm.add_transition(state1, state2, [&](){
		if (contador++ >= 5) {
			contador = 0;
			return true;
		}

		return false;
	});

	general_sm.add_transition(state2, state1, [&](){
		if (contador++ >= 5) {
			contador = 0;
			return true;
		}

		return false;
	});

	Time::register_low_precision_alarm(300, [&](){
		general_sm.check_transitions();
	});

	Time::register_low_precision_alarm(50, [&](){
		STLIB::update();
	});
	while(1) {
		__NOP();
	}
}

void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
	ErrorHandler("HAL error handler triggered");
  /* User can add his own implementation to report the HAL error return state */
  //__disable_irq();
  //while (1){}
  /* USER CODE END Error_Handler_Debug */
}
```

2023-02-21 19:24 UTC, PabloGonzalezSegarra requested changes

2023-02-21 19:24 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +using std::map;
Esto en C++Utilities

2023-02-21 19:24 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	void add_state_machine(StateMachine& state_machine, uint8_t state);
```suggestion
	void add_nested_state_machine(StateMachine& state_machine, uint8_t state);
```

2023-02-21 19:24 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	map<uint8_t, StateMachine*> nested_state_machine;
```suggestion
	unordered_map<uint8_t, StateMachine*> nested_state_machine;
```

2023-02-21 19:24 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
> +	if (current_state != state) {
Porque este if si no esta en el mismo estado?

2023-02-22 09:11 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
> +	if (current_state != state) {
Si nesteas una SM, y el estado al que la nesteas no es el actual, hay que apagarla para que no ejecute nada.

2023-02-22 09:11 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	map<uint8_t, StateMachine*> nested_state_machine;
Da error de hashes

2023-02-22 09:12 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	void add_state_machine(StateMachine& state_machine, uint8_t state);
Es un poco redundante, ya sabes que es nested, pq es un metodo de instancia

2023-02-22 17:39 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	map<uint8_t, StateMachine*> nested_state_machine;
no deberia pero ueno

2023-02-27 15:32 UTC, StefanCostea approved these changes

2023-02-27 15:32 UTC, StefanCostea commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
>  	unordered_map<uint8_t, State> states;
yo haria un typedef iterno de la clase de uint8 a state_id para que quede mas legible

2023-02-28 08:39 UTC, PabloGonzalezSegarra requested changes

2023-02-28 08:39 UTC, PabloGonzalezSegarra commented on Src/ST-LIB.cpp
> +	//Ethernet::update();
Esto descomentalo.

2023-02-28 10:15 UTC, StefanCostea approved these changes

2023-02-28 12:07 UTC, merged