basic RTC
HyperloopUPV-H8/ST-LIB pull request #214
Opened 2023-02-21 17:36 UTC by ricardochust

in this pull request i will put the squeleton of the RTC, which is configuration, get data and set data. 
there will be a follow-up pull request about the SMTP so we cano focus on the RTC structure on this one and the handling of an SMTP client on the next one.

2023-02-21 18:42 UTC, alejandrogonzalvo requested changes

2023-02-21 18:42 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Time/Time.hpp
> +	struct rtc_data{
```suggestion
	struct RTCData{
```

2023-02-21 18:42 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Time/Time.cpp
> +
Borra todos los comentarios de la HAL

2023-02-21 18:42 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Time/Time.cpp
> +
@StefanCostea Deberia haber una funcion que devuelva un string con la hora ya formateada para time stamping.

2023-02-21 19:15 UTC, PabloGonzalezSegarra requested changes
Hay que revisar que la configuracion esta para el RTC tambien sea compatible con las placas. Y porfavor empieza las frases con mayusculas que me va a petar una vena xD.

2023-02-21 19:15 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/Time/Time.hpp
> +#define RTC_max_counter 32767
```suggestion
#define RTC_MAX_COUNTER 32767
```

2023-02-21 19:15 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/Time/Time.hpp
> +	static void set_RTC_data(uint16_t counter, uint8_t second, uint8_t minute, uint8_t hour, uint8_t day, uint8_t month, uint16_t year);
```suggestion
	static void start_rtc();
	static rtc_data get_rtc_data();
	static void set_rtc_data(uint16_t counter, uint8_t second, uint8_t minute, uint8_t hour, uint8_t day, uint8_t month, uint16_t year);
```

2023-02-23 19:39 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +
depende como lo formateemos en los paquetes, dependiendo de el formato del struct casi que prefiero esto ya no es dinamico, recordad que añadir cosas dinamicas dentro de los paquetes los hace el doble de lentos

2023-02-23 19:44 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +
lo hablare con ricardo y vere exactamente como tiene que formatearse el struct para que sea un struct estatico pero que el binario quede solo la informacion relevante y en un orden concreto

2023-02-24 09:39 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Time/Time.cpp
> +
ok, resuelvo

2023-03-07 14:20 UTC, ricardochust commented
como he tenido que hacer varios cambios a RTC para adaptarlo a SNTP voy a pasar todo al pull request de SNTP. Los cambios que habeis pedido ya se han hecho alli.

2023-03-09 06:40 UTC, alejandrogonzalvo commented
cierra este pues

2023-03-13 18:40 UTC, closed without merging