Features/sntp
HyperloopUPV-H8/ST-LIB pull request #217
Opened 2023-03-03 15:32 UTC by ricardochust

SNTP working

you need to change the configuration on the .ioc lwip to enable sntp, which will generate a sntp.c in Middlewares/ThirdParty/lwip/src/apps/sntp/sntp.c

Then you will need to add a piece of code which configurates the sntp in Middlewares/ThirdParty/lwip/include/lwip/apps/sntp_opts.h just below the includes. This is the code:

```
static void set_time(uint32_t sec, uint32_t us);
static void set_rtc(uint16_t counter, uint8_t second, uint8_t minute, uint8_t hour, uint8_t day, uint8_t month, uint16_t year);

#define SNTP_STARTUP_DELAY 0
#define SNTP_SET_SYSTEM_TIME_US(sec,us) set_time(sec,us)
#define SUBSECONDS_PER_SECOND 32767
#define TRANSFORMATION_FACTOR 0.032767 //SUBESCONDS_PER_SECOND / 10000000. Directly calculated to skip division as each operation adds a difference between time received and time saved
#define SNTP_COMP_ROUNDTRIP 1

void set_time(uint32_t sec, uint32_t us){
	struct timeval tv;
	tv.tv_sec = sec;
	tv.tv_usec = us;
	time_t nowtime = sec;
	struct tm *nowtm = localtime(&nowtime);
	uint32_t subsecond = (uint32_t)(TRANSFORMATION_FACTOR * tv.tv_usec);
	set_rtc(subsecond, nowtm->tm_sec, nowtm->tm_min, nowtm->tm_hour, nowtm->tm_mday, 1+nowtm->tm_mon, 1900+(nowtm->tm_year));
}
```

Also you will need to follow the Ethernet configuration (step 7 and below) as you will need to generate code so the sntp.c is created, which will remove the Ethernet configuration (and it is needed for sntp)

2023-03-03 15:33 UTC, ricardochust commented
There is a bug where the year is not correctly set, but it is a bug on the rtc side and i will attend it on the rtc pull request

2023-03-13 18:51 UTC, PabloGonzalezSegarra requested changes

2023-03-13 18:51 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/Communication/SNTP/SNTP.hpp
> +//tontos usando sntp para configurar rtc
Quita esto

2023-03-13 18:51 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/Communication/SNTP/SNTP.hpp
> +	static void sntp_update(uint8_t address_head, uint8_t address_second, uint8_t address_third, uint8_t address_last);
Aqui seria mejor pasar un string como hace stefan en la clase ethernet o en el STLIB::start

2023-03-13 18:51 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/SNTP/SNTP.cpp
> +extern "C" void set_rtc(uint16_t counter, uint8_t second, uint8_t minute, uint8_t hour, uint8_t day, uint8_t month, uint16_t year){
porque el extern?

2023-03-14 11:19 UTC, ricardochust commented on Src/HALAL/Services/Communication/SNTP/SNTP.cpp
> +extern "C" void set_rtc(uint16_t counter, uint8_t second, uint8_t minute, uint8_t hour, uint8_t day, uint8_t month, uint16_t year){
el extern es porque se usa dentro de sntp_opts.h, que esta en C. Le hace falta acceder al rtc para cambiar la fecha y esa funcion hace de puente para ello.

2023-03-14 11:20 UTC, ricardochust commented on Inc/HALAL/Services/Communication/SNTP/SNTP.hpp
> +//tontos usando sntp para configurar rtc
ups

2023-03-14 15:30 UTC, ricardochust commented on Inc/HALAL/Services/Communication/SNTP/SNTP.hpp
> +	static void sntp_update(uint8_t address_head, uint8_t address_second, uint8_t address_third, uint8_t address_last);
done

2023-03-17 15:25 UTC, StefanCostea approved these changes

2023-03-17 15:25 UTC, StefanCostea commented on Src/HALAL/Services/Communication/SNTP/SNTP.cpp
> +void SNTP::sntp_update(string ip) {
esto es un start no un update

2023-03-21 09:36 UTC, PabloGonzalezSegarra approved these changes

2023-03-22 13:23 UTC, merged