PWM Rework
HyperloopUPV-H8/ST-LIB pull request #219
Opened 2023-03-10 09:08 UTC by alejandrogonzalvo

Falta validar, hare una explicacion aquí de todo cuando este en ready

2023-03-10 13:39 UTC, ricardochust requested changes

2023-03-10 13:39 UTC, ricardochust commented on Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
> +extern TIM_HandleTypeDef htim2;
eliminar timer 2,5,6, y 24 de aqui si no se va a usar, para evitar problemas con la clase Time

2023-03-13 18:54 UTC, PabloGonzalezSegarra requested changes

2023-03-13 18:54 UTC, PabloGonzalezSegarra commented on Src/HALAL/HALAL.cpp
> +	//Ethernet::start(ip, subnet_mask, gateway);
No subas esto comentado

2023-03-13 18:54 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB.hpp
> +			string ip = "192.168.1.0",
pon por defecto la 192.168.1.4 que es la que hemos estado usando de forma standard mejor

2023-03-13 18:54 UTC, PabloGonzalezSegarra commented on Src/ST-LIB.cpp
> +    //Ethernet::update();
lo mismo, no comentes esto

2023-03-13 18:54 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/DigitalOutput/DigitalOutput.cpp
> +#include <DigitalOutput/DigitalOutput.hpp>
ponlo con comillas

2023-03-13 18:54 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/HalfBridge/HalfBridge.cpp
> +	DigitalOutputService::turn_on(enable); // enable al final para evitar ruido
Si quieres dejar un comentario ponlo en ingles

2023-03-14 11:23 UTC, ricardochust approved these changes
lo voy aprobando asumiendo que cumplas lo que te pidio pablo

2023-03-17 15:32 UTC, StefanCostea requested changes

2023-03-17 15:32 UTC, StefanCostea commented on Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
> +#define DualPWMmap map<pair<Pin, Pin>, pair<reference_wrapper<TimerPeripheral>, TimerPeripheral::PWMData>>
usa un typedef

2023-03-17 15:32 UTC, StefanCostea commented on Inc/HALAL/Services/PWM/PhasedPWM/PhasedPWM.hpp
> +	void set_phase(float phase);
respecto a que se hace la fase? imagino que solo se pueden desfasar pwms de timers que compartan peripheral clock, eso se comprueba?

2023-03-17 15:32 UTC, StefanCostea commented on Src/HALAL/Services/PWM/PWM/PWM.cpp
> +	ErrorHandler("This PWM instance does not support phasing");
quitalo

2023-03-17 15:32 UTC, StefanCostea commented on Src/HALAL/Services/PWM/PWM/PWM.cpp
> +	ErrorHandler("This PWM instance does not support phasing");
si no lo soporta mueve la funcion de clase

2023-03-17 15:33 UTC, StefanCostea commented
No te olvides cambiar el project template y las runas cuando se pushee

2023-03-17 16:51 UTC, alejandrogonzalvo commented on Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
> +#define DualPWMmap map<pair<Pin, Pin>, pair<reference_wrapper<TimerPeripheral>, TimerPeripheral::PWMData>>
no funciona, TimerPeripheral no está declarado y da error.

2023-03-21 09:41 UTC, PabloGonzalezSegarra requested changes

2023-03-21 09:41 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/DigitalOutput/DigitalOutput.hpp
porque cambias esto de sitio?

2023-03-21 09:41 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/DualPWM/DualPWM.cpp
> +	HAL_TIMEx_PWMN_Start(peripheral->handle, channel);
Comprueba siempre que las funciones de la HAL te devuelven HAL_OK

2023-03-21 09:41 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PWM/PWM.cpp
> +	HAL_TIM_PWM_Start(peripheral->handle, channel);
Lo mismo, comprueba que te devuelven HAL_OK

2023-03-21 09:41 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PWM/PWM.cpp
> +	HAL_TIM_PWM_Start(peripheral->handle, channel);
Hazlo con todas

2023-03-21 09:41 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PhasedPWM/PhasedPWM.cpp
> +#include <PWM/PhasedPWM/PhasedPWM.hpp>
Comillas ""

2023-03-21 09:41 UTC, PabloGonzalezSegarra commented on Src/ST-LIB.cpp
> +    //Ethernet::update();
No dejes esto comentado

2023-03-24 14:46 UTC, StefanCostea approved these changes

2023-03-24 15:38 UTC, Dgoncas approved these changes

2023-03-24 16:35 UTC, merged