Fix/bootloader changes
HyperloopUPV-H8/ST-LIB pull request #222
Opened 2023-03-13 18:38 UTC by PabloGonzalezSegarra

Necesary fixes for bootloader

2023-03-13 20:10 UTC, alejandrogonzalvo requested changes
Quita todo lo relacionado con time. git checkout development --time.hpp para restorearlo a dev, lo mismo con el cpp

2023-03-13 20:10 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Time/Time.hpp
> +		uint64_t offset;
Esto no va en este PR, hay uno abierto ya que arregla eso

2023-03-17 15:40 UTC, StefanCostea requested changes

2023-03-17 15:40 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +			.offset = (Time::low_precision_tick),
quita todas las modificaciones de time que hayas hecho

2023-03-20 13:41 UTC, Dgoncas approved these changes

2023-03-22 08:06 UTC, PabloGonzalezSegarra commented
Todo resuelto .👍

2023-03-24 13:36 UTC, ricardochust approved these changes

2023-03-30 09:57 UTC, alejandrogonzalvo approved these changes

2023-03-31 13:35 UTC, hyperloop-orangeman commented
hola

2023-03-31 13:43 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 2023-03-31-13-42-10

2023-03-31 13:51 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:51:09 de 31/03/2023; Ultima modificacion del PR: 13:48:12 de 31/03/2023

2023-03-31 13:52 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:52:55 de 31/03/2023; Ultima modificacion del PR: 13:51:09 de 31/03/2023

2023-03-31 13:54 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:54:30 de 31/03/2023; Ultima modificacion del PR: 13:52:55 de 31/03/2023

2023-03-31 13:54 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:54:49 de 31/03/2023; Ultima modificacion del PR: 13:54:30 de 31/03/2023

2023-03-31 13:56 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:56:12 de 31/03/2023; Ultima modificacion del PR: 13:54:50 de 31/03/2023

2023-03-31 13:57 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 13:57:04 de 31/03/2023; Ultima modificacion del PR: 13:56:12 de 31/03/2023

2023-03-31 14:00 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:00:51 de 31/03/2023; Ultima modificacion del PR: 13:57:04 de 31/03/2023

2023-03-31 14:21 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:21:16 de 31/03/2023; Ultima modificacion del PR: 14:00:52 de 31/03/2023

2023-03-31 14:22 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:22:24 de 31/03/2023; Ultima modificacion del PR: 14:22:09 de 31/03/2023

2023-03-31 14:24 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:24:38 de 31/03/2023; Ultima modificacion del PR: 14:24:01 de 31/03/2023

2023-03-31 14:25 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:25:00 de 31/03/2023; Ultima modificacion del PR: 14:24:39 de 31/03/2023

2023-03-31 14:25 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:25:18 de 31/03/2023; Ultima modificacion del PR: 14:25:01 de 31/03/2023

2023-03-31 14:31 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:31:57 de 31/03/2023; Ultima modificacion del PR: 14:25:19 de 31/03/2023

2023-03-31 14:37 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:37:29 de 31/03/2023; Ultima modificacion del PR: 14:37:03 de 31/03/2023

2023-03-31 14:37 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:37:42 de 31/03/2023; Ultima modificacion del PR: 14:37:29 de 31/03/2023

2023-03-31 14:39 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:39:16 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 14:39 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:39:47 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 14:43 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:43:04 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 14:48 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 14:48:57 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 15:14 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:14:25 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 15:15 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:15:12 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 15:58 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:58:48 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:02 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:02:43 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:03 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:03:12 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:03 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:03:36 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:07 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:07:11 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:09 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:09:30 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:14 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:14:42 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:15 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:15:16 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:16 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 16:16:45 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:21 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:21:35 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:35 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:35:37 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:36 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:36:42 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 16:50 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 18:50:30 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 17:08 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 19:08:09 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-03-31 17:10 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 19:10:43 de 31/03/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-04-04 13:22 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:22:54 de 04/04/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-04-04 13:24 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:24:50 de 04/04/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-04-04 13:33 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:33:30 de 04/04/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-04-04 13:35 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:35:00 de 04/04/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-04-04 13:39 UTC, hyperloop-orangeman commented
texto automatizado de orange-man. Ultima fecha de revision del PR: 15:39:48 de 04/04/2023; Ultima modificacion del PR: f2dc1a8832d099479bdb09dd1d400662fbc6e0bd

2023-04-17 14:19 UTC, merged