Features/cproject fix
HyperloopUPV-H8/ST-LIB pull request #23
Opened 2022-10-28 09:16 UTC by alejandrogonzalvo

**Features/cproject fix**
This PR solves all the problems with include and explains how to link STLIB with an external project. More info on this issue:
Features/cproject fix

TODO: Upload template project.

2022-10-28 10:23 UTC, PabloGonzalezSegarra commented
@alejandrogonzalvo  ves con mucho más cuidado con los pull request, habías puesto que el merge sea a la main en vez de la HALAL. Además recuerda etiquetar a la gente.

2022-10-28 10:31 UTC, PabloGonzalezSegarra approved these changes
Esta bien pero el próximo PR que intentes hacer merge a main te lo cierro.

2022-10-29 11:57 UTC, PabloGonzalezSegarra requested changes
No subas la carpeta .settings porque contiene tus preferencias del proyecto. En el PR que estoy haciendo la incluiré en el gitignore por ahora no la subas.

2022-10-29 12:01 UTC, PabloGonzalezSegarra commented on .cproject
> +								<option IS_BUILTIN_EMPTY="false" IS_VALUE_EMPTY="false" id="com.st.stm32cube.ide.mcu.gnu.managedbuild.tool.assembler.option.definedsymbols.38266524" name="Define symbols (-D)" superClass="com
Porque has añadido la opcion : useByScannerDiscovery="false" ?

2022-10-29 12:02 UTC, PabloGonzalezSegarra commented on .cproject
> +									<listOptionValue builtIn="false" value="&quot;${workspace_loc:/ST-LIB/Inc/HALAL/Services/*}&quot;"/>
Sobra el asterisco

2022-10-29 12:03 UTC, PabloGonzalezSegarra commented on .cproject
> +									<listOptionValue builtIn="false" value="&quot;${workspace_loc:/ST-LIB/Inc/HALAL/Services/*}&quot;"/>
sobra el asterisco

2022-10-29 12:04 UTC, PabloGonzalezSegarra reviewed
Recuerda hacer todos los cambios desde el cube

2022-10-29 16:41 UTC, PabloGonzalezSegarra approved these changes

2022-10-29 16:42 UTC, PabloGonzalezSegarra commented
Ya esta perfecto, lo he probado y compila.

2022-10-29 17:03 UTC, StefanCostea approved these changes

2022-10-29 18:53 UTC, merged