Fix/protections
HyperloopUPV-H8/ST-LIB pull request #244
Opened 2023-04-22 15:41 UTC by StefanCostea

Rework done to Protection Manager

2023-04-25 16:31 UTC, alejandrogonzalvo submitted a review, later dismissed

2023-04-28 10:37 UTC, PabloGonzalezSegarra requested changes
Muchos cambios hay que tener cuidado.

2023-04-28 10:37 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/FDCAN.cpp
Como????

2023-04-28 10:37 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/DualPhasedPWM/DualPhasedPWM.cpp
> +#include <PWM/DualPhasedPWM/DualPhasedPWM.hpp>
Volver a las comillas

2023-04-28 10:37 UTC, PabloGonzalezSegarra commented on .cproject
> +									<listOptionValue builtIn="false" value="HSE_VALUE=25000000UL"/>
y esto?

2023-04-28 10:37 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/FDCAN.cpp
Porque habeis movido el FDCAN al uart?

2023-04-29 18:24 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/FDCAN.cpp
esto sigue mal, cuidado

2023-05-03 16:37 UTC, ricardochust submitted a review, later dismissed

2023-05-10 07:59 UTC, PabloGonzalezSegarra approved these changes

2023-05-10 19:53 UTC, StefanCostea commented on Inc/ST-LIB_HIGH/Protections/Boundary.hpp
> +	static int get_error_handler_string_size(){
que pereza cambiarlo en todos lados

2023-05-11 07:05 UTC, PabloGonzalezSegarra approved these changes

2023-05-11 07:05 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
>  void Ethernet::mpu_start(){
Esta MPU sigue jodiendo la flash

2023-05-11 17:15 UTC, StefanCostea commented on Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
>  void Ethernet::mpu_start(){
eso lo tendremos que arreglar mas tarde

2023-05-11 17:16 UTC, merged