Add folder structure
HyperloopUPV-H8/ST-LIB pull request #27
Opened 2022-10-31 18:22 UTC by ricardochust

# New branch FolderStructure for the STLIB
New folders ST-LIB_LOW created both in src and inc. In src goes the cpp and in inc the hpp.

Do not split in models and services sub-folders, put all modules directly in ST-LIB_LOW folders.

Example of use:

![image](https://user-images.githubusercontent.com/116189892/199080985-c79b2895-85f7-41fd-897f-1f57ee73cf76.png)

2022-10-31 18:49 UTC, StefanCostea requested changes
Add "Sensors" intermediate folder between STLIB LOW and LinearSensor., DigitalSensor etc...

2022-11-01 10:02 UTC, ricardochust commented
> Add "Sensors" intermediate folder between STLIB LOW and LinearSensor., DigitalSensor etc...

Change added.

2022-11-01 11:02 UTC, merycuesta approved these changes

2022-11-01 12:19 UTC, StefanCostea approved these changes

2022-11-01 12:19 UTC, merged