protection manager changes
HyperloopUPV-H8/ST-LIB pull request #318
Opened 2023-06-17 11:56 UTC by ricardochust

Changes added:

Changed IP of SNTP to the actual server IP (tested)

Put enum of faultType into a namespace so the global space isn t polluted with enums that are not meant to be used there (like FAULT)

Made that when the protection handler goes to fault it first sends a packet with ID 0 to all sockets to get all boards into fault faster. (tested)

For now the ProtectionManager sends this fast packet once when it forces the GeneralStateMachine into fault. There is also a method called propagate_fault for anyone that needs it, but if any other behaviour is prefered for all boards let me know here.

![image](https://github.com/HyperloopUPV-H8/ST-LIB/assets/116189892/5f4a7132-304d-4c51-9809-6a1202d12f61)

TODO:

add Error as a part of protection handler (for tomorrow)

2023-06-17 13:09 UTC, StefanCostea requested changes

2023-06-17 13:09 UTC, StefanCostea commented on Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
>  Notification ProtectionManager::fault_notification = {ProtectionManager::fault_id, ProtectionManager::to_fault};
remove callback

2023-06-17 13:09 UTC, StefanCostea commented on Inc/ST-LIB_HIGH/Protections/Protection.hpp
> +namespace protections{
use upper case

2023-06-17 13:09 UTC, StefanCostea commented on Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
> +StackOrder<0> ProtectionManager::fault_order(0,to_fault);
id should not be hardcoded

2023-06-19 18:13 UTC, StefanCostea approved these changes

2023-06-19 18:13 UTC, StefanCostea commented on Inc/ST-LIB_HIGH/ST-LIB_HIGH.hpp
> +namespace STLIB_HIGH {
mete el stlib high start en el stlib start

2023-06-20 18:11 UTC, PabloGonzalezSegarra approved these changes

2023-06-21 22:25 UTC, ricardochust commented on Inc/ST-LIB_HIGH/ST-LIB_HIGH.hpp
> +namespace STLIB_HIGH {
> mete el stlib high start en el stlib start

hecho (esta en ST-LIB.cpp)

2023-06-21 22:27 UTC, ricardochust commented on Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
>  Notification ProtectionManager::fault_notification = {ProtectionManager::fault_id, ProtectionManager::to_fault};
done

2023-06-21 22:29 UTC, ricardochust commented on Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
>  Notification ProtectionManager::fault_notification = {ProtectionManager::fault_id, ProtectionManager::to_fault};
Si quieres déjate esto hasta que haga los test mañana por la mañana y cuando confirme mergeamos
(o no, porque ya comprobé que funcionaba sin el de antemano, es una precaucion un poco excesiva pero a mi me mola asegurar)

2023-06-21 22:51 UTC, merged