Features/ic
HyperloopUPV-H8/ST-LIB pull request #32
Opened 2022-11-07 12:21 UTC by alejandrogonzalvo

### Input Capture Service
The IC service abstracts configuration of the IC mode of the timer peripheral on the stm32H723.

_**Testing**_
It has been proven to work on duty cycles ranging from 1% to 99%.
![IC2](https://user-images.githubusercontent.com/59616818/200307219-979bec15-a4e5-4c08-8f66-4512fd94e002.png)

It has been proven to work on frequencies up to 4800Hz.
![IC2](https://user-images.githubusercontent.com/59616818/200307444-673c8c2e-3dc2-4eba-9949-f082114e253d.png)

It has been detected an error due to a whole cycle being skipped.
Real frequency 10000Hz. Freq Shown 5000Hz.
![ICerror](https://user-images.githubusercontent.com/59616818/200307628-b1a21a0d-47d8-4c9c-80a7-4e55ccac9ba4.png)

All the testing has been done connecting a PWM to an IC configured on different timers.

_**Usage**_
In order to use it you register the IC instance by passing a pin to the IC::register_ic(Pin) function. 
Then you call Pin::Start after registering all your peripherals.
Finally, you just turn it on. See the example used for testing:
![image](https://user-images.githubusercontent.com/59616818/200308676-0b23fb88-a75d-4997-909c-827231b6f932.png)

2022-11-07 13:30 UTC, StefanCostea commented
Post a pic of your ioc configuration please

2022-11-07 13:54 UTC, alejandrogonzalvo commented
PWM:
![image](https://user-images.githubusercontent.com/59616818/200326260-5cf990ee-8889-4f91-9027-7bef4d72b51a.png)
![image](https://user-images.githubusercontent.com/59616818/200326367-f04e6168-6b67-47f7-8fc1-3efbd932c537.png)
![image](https://user-images.githubusercontent.com/59616818/200326728-0509758f-4246-45b0-9d3d-18d86b4a2ae1.png)

IC:
![image](https://user-images.githubusercontent.com/59616818/200326891-240fff9b-e5ad-41bc-bf7a-443bd7592004.png)
![image](https://user-images.githubusercontent.com/59616818/200326966-3612c06d-6989-4ee2-ab68-389f53e52a19.png)
![image](https://user-images.githubusercontent.com/59616818/200327474-67eb61e5-240a-46bb-a932-8c006e0c6fd4.png)
![image](https://user-images.githubusercontent.com/59616818/200327051-b11bd2fb-1e14-4317-89e9-f34102731a4f.png)

2022-11-07 18:15 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/InputCapture/InputCapture.cpp
> +map<uint8_t,Pin> IC::service_ids = {};
Te falta un espacio
```suggestion
map<uint8_t, Pin> IC::service_ids = {};
```

2022-11-07 18:38 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/InputCapture/InputCapture.cpp
> +			return {pin_timer.second.channel_rising, pin_timer.second.channel_falling};
Esto esta feo molaría un refactor de alguna manera

2022-11-07 18:48 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/InputCapture/InputCapture.cpp
> +			break;
te sobran lineas en blanco

2022-11-07 18:48 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/InputCapture/InputCapture.cpp
> +			else if (ic_data.counter_values[1] > ic_data.counter_values[2]) {
no dejes lieneas en blanco que no se entiende nada

2022-11-07 19:10 UTC, PabloGonzalezSegarra reviewed
Revisa mis comentarios

2022-11-07 20:17 UTC, StefanCostea requested changes

2022-11-08 17:10 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/InputCapture/InputCapture.cpp
> +			else if (ic_data.counter_values[0] > ic_data.counter_values[2]) {
no dejes else if con líneas en blanco encima, entiendo que quieras fardar de que tu código tienes muchas líneas pero las que esta en blanco no cuentan

2022-11-09 11:57 UTC, alejandrogonzalvo commented on Src/HALAL/Services/InputCapture/InputCapture.cpp
> +			else if (ic_data.counter_values[0] > ic_data.counter_values[2]) {
bruh

2022-11-11 13:18 UTC, StefanCostea commented
Implementalo como en el PR que propusiste, echale un ojo a https://controllerstech.com/pwm-input-in-stm32/  aqui la implementacion que hace es mucho mas simple

2022-11-12 16:50 UTC, closed without merging