Features/time
HyperloopUPV-H8/ST-LIB pull request #36
Opened 2022-11-10 18:36 UTC by Dgoncas

**DESCRIPCION**

Time esta hecho para abstraer el uso de timers con el objetivo de medir tiempos de ejecucion, frecuencia y crear tareas que se eejecutan cada X tiempo o de manera periodica.

Para manejar hacer leer y medir tiempos de ejecucion se reserva un timer global de la maxima resolucion (3,3ns), se usa con la funcion get_global_tick().

Para ejecutar tareas periodicas puedes hacer 2 cosas : 

- Ejectuar un loop cada X tiempo que revise si es hora de hacer esa tarea
-  Reserver un timer que lo haga

Las 2 opciones tienen sus ventajas y desventajas, por eso se han implementado ambas,  unas con un timer de alta resolucion que configura un callback y otra con un loop que se ejcuta cada ms.

**USO DEL MODULO**

![image](https://user-images.githubusercontent.com/71754670/201178547-5284ae23-60cc-42d5-90cd-3ba58dfc132b.png)

**DIAGRAMA MODIFICADO**

![image](https://user-images.githubusercontent.com/71754670/201178423-34ba760c-1e0c-42db-9ba6-ac96ad463dab.png)

2022-11-11 07:39 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/ADC/ADC.cpp
> +	return {};
Devuelve nullopt es mas limpio

2022-11-11 07:49 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Time/Time.cpp
> +// HAL TIMER CALLBACK
Evitar comentarios redundantes

2022-11-11 07:52 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/ADC/ADC.cpp
> +	return {};
Porque modificas el ADC en esta rama?

2022-11-11 12:46 UTC, StefanCostea commented
Los high precision timers los configuras mediante el ioc? igual deberias hacer que tu clase los configure el Time::Start sobreescribiendo el init de la HAL para evitar problemas

2022-11-11 12:46 UTC, StefanCostea commented
Resuelve los conflictos haciendo merge de la halal a tu rama y vuelve a hacer push a tu rama

2022-11-11 12:46 UTC, StefanCostea requested changes

2022-11-11 12:46 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +			Time::high_precision_timer_callback(tim);
Estas usando count para ver si tim esta en el set? si es el caso puedes usar contains

2022-11-11 12:50 UTC, StefanCostea commented
El setTimeout como funciona? ejecuta el callback que le indicas una sola vez?

2022-11-11 12:51 UTC, StefanCostea requested changes

2022-11-11 12:51 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +	Time::Alarm alarm = { period_in_us, low_precision_timer, func };
```suggestion
	Time::Alarm alarm = { .period = period_in_us, 
	.tim = low_precision_timer,
	.alarm = func };
```

2022-11-11 12:52 UTC, StefanCostea commented
Porque has hecho el sistema de ids de manera diferente al resto??

2022-11-11 13:22 UTC, Dgoncas commented on Src/HALAL/Services/ADC/ADC.cpp
> +	return {};
Habia un warning por no poner un return

2022-11-12 18:10 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Time/Time.cpp
> +	Time::Alarm alarm = { period_in_us, low_precision_timer, func };
Me parece bien pero que lo `.nombre = valor ` esten alineados que queda mejor.
 . . . . . . . . . . . . . . . . . . . . . . . . . .`.nombre2 = valor2`

2022-11-15 08:43 UTC, PabloGonzalezSegarra commented
Solo has pasado esos test?

2022-11-19 18:38 UTC, StefanCostea requested changes

2022-11-19 18:38 UTC, StefanCostea commented on Inc/HALAL/Services/Time/Time.hpp
> +	static uint8_t register_low_precision_alarm(uint32_t period_in_ms, function<void()> func);
should return optional

2022-11-19 18:38 UTC, StefanCostea commented on Inc/ST-LIB_LOW/Clocks/Counter.hpp
> +	Counter(uint64_t v);
whats v?

2022-11-19 18:38 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +uint8_t Time::register_low_precision_alarm(uint32_t period_in_ms, function<void()> func){
correct with optional

2022-11-19 18:44 UTC, StefanCostea requested changes

2022-11-19 18:44 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +	if(Time::low_precision_alarms_by_id.find(id) == low_precision_alarms_by_id.end())
use contains

2022-11-19 18:44 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +		return {};
nullopt

2022-11-19 18:44 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +	Time::Alarm alarm = { period_in_us, tim, func };
.period = period_in_us,
.tim = tim,
.alarm = func

2022-11-19 18:44 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +	if(Time::high_precision_alarms_by_id.find(id) == high_precision_alarms_by_id.end())
use contains

2022-11-19 18:44 UTC, StefanCostea commented on Src/HALAL/Services/Time/Time.cpp
> +	Time::Alarm alarm = { period_in_ms, low_precision_timer, func };
.period = period_in_ms,
.tim = low_precision_timer,
.alarm = func

2022-11-25 16:32 UTC, alejandrogonzalvo approved these changes

2022-11-25 16:33 UTC, merged