Features/sensor (no merge)
HyperloopUPV-H8/ST-LIB pull request #38
Opened 2022-11-14 17:25 UTC by ricardochust

Pull request for sensor fork to ease of check. 

Not tested yet, do NOT merge

2022-11-14 17:50 UTC, PabloGonzalezSegarra commented on .gitignore
> +.settings/language.settings.xml
No modifiques el .gitignore en esta rama

2022-11-14 17:54 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	double counter_distance;
La distancia entre  tapes va a ser siempre la misma y constante, por tanto no tiene sentido pedirla en el construtor.
Mejor ha un `#define DISTANCE 25` por ejemplo.

2022-11-14 17:56 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +	optional<uint8_t> identification = Encoder::register_encoder(pin1,pin2);
Aquí ponle un nombre tipo result o algo asi para que quede mas claro.

2022-11-14 17:57 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		//errores de optional vacio aqui (por hacer)
Cuanndo hagas estos comentarios incidcando que queda algo por hacer añade un TODO: delante. Así despues el Cube te indica todos los TODO que te faltan y no te dejas ninguno.
```suggestion
		//TODO: Error handler, Error during register of encoder x
```

2022-11-14 18:03 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		*position= sign * ((double) counter.value()) * counter_distance;
La dirección solo puede ser positiva y es absoluta al incio del tubo.
Tubo-> =========================================
. . . . . . . ^ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ^
________Siempre es el 0 ___________________________________________________Siempre es la distancia máxima

2022-11-14 18:03 UTC, ricardochust commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	double counter_distance;
sabemos ya la distancia? lo digo por poner el numero ya

2022-11-14 18:11 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		*acceleration = (*speed - last_speed) * clock_frequency/ (check - last_check);
Ese `check - last_check` se le llama _delta time_. Por tanto para mas claredad lo que puedes hacer para que quede mejor es:
`delta_time = Time::get_global_tick() - last_time;`
...Codigo... (Substituyendo el `check - last_check` por `delta_time` )
`last_time += delta_time;`

2022-11-14 18:16 UTC, PabloGonzalezSegarra commented
> The Encoder returns 3 values on pointers given on the constructor: position, speed and acceleration

También deberías poder obtener la dirección, pues más adelante hará falta saber en que dirección nos movemos. Lo que se puede hacer es tener un enum por ejemplo: 
`enum Direction{
    forward,
    backward,
}`
Y sea uno de estos dos valores lo que devuelves, como en los enums el primer valor es 0 y el segundo 1 se infiere solo y es mas fácil para el que usa el encoder interpretar el resultado.

2022-11-14 18:17 UTC, PabloGonzalezSegarra commented
Cuando hagas commits añade una pequeña descripción no pongas solo Update EncoderSensor.cpp para que el resto entendamos más fácilmente que has modificado en cada commit.

2022-11-14 18:19 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	double counter_distance;
Aun no, pon 25(mm) que es el que usábamos el año pasado y ya lo cambiaremos.

2022-11-14 18:20 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		last_check += delta_time;
Usa `last_time` mejor que queda muy claro, check no se sabe que es a simple vista.

2022-11-14 18:21 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		//errores de optional vacio aqui (por hacer)
Lo de los TODO: hazlo en todos los comentarios del estilo como este,

2022-11-14 18:26 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		*speed = (*position - last_position) * clock_frequency / (delta_time);
Aquí vas a tener problemas porque vas a leer varias veces entre tapes porque el reloj va muy rápido por tanto el CNT no habrá cambiado y la velocidad será 0 varias veces y de repente el valor real  y otra vez muchos 0. Tienes que pensar como solucionar esto. La solución del año pasado era una chapuza y por tanto no funcionaba del todo bien, cuando se te haya ocurrido algo me avisas.

2022-11-14 18:27 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		*acceleration = (*speed - last_speed) * clock_frequency/ (delta_time);
La aceleración sufrirá de lo mismo porque por el mismo hecho.

2022-11-14 18:28 UTC, ricardochust commented
> > The Encoder returns 3 values on pointers given on the constructor: position, speed and acceleration
> 
> También deberías poder obtener la dirección, pues más adelante hará falta saber en que dirección nos movemos. Lo que se puede hacer es tener un enum por ejemplo: `enum Direction{ forward, backward, }` Y sea uno de estos dos valores lo que devuelves, como en los enums el primer valor es 0 y el segundo 1 se infiere solo y es mas fácil para el que usa el encoder interpretar el resultado.

Se puede saber ya la direccion con el signo de la velocidad (positivo hacia delante, negativo hacia detras), pero si lo preferiis puedo hacer que sea un parametro del constructor que se actualice en el read, como lo son position, speed y acceleration o que sea dado por un metodo aparte en caso de que se revisen en situaciones muy distintas

2022-11-14 18:30 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		int sign = (1 - 2*direction.value());
esto ya no te hace falta

2022-11-14 18:34 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	double counter_distance = 0.025;
no te calientes, mételo en un #define mejor en el .hpp

2022-11-14 18:34 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	double counter_distance = 0.025;
Todas las constantes déjalas en #define que queda mas claro

2022-11-14 18:41 UTC, ricardochust commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		int sign = (1 - 2*direction.value());
sigo necesitando traducir el signo a positivo/negativo para poder calcular la aceleración en caso de cambio de sentido (ya que resta velocidades, si son signos contrarios las suma), pero como aun tengo que arreglar el tema de velocidad y aceleración 0, veré si con la nueva implementación hace falta o no

2022-11-14 18:50 UTC, ricardochust commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	double counter_distance = 0.025;
hecho

2022-11-14 23:18 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		int sign = (1 - 2*direction.value());
No veo porque lo necesitarías, pero bueno no te atosigo más con comentarios xD en general tiene buena pinta. Cuando la tengas más avanzada le volveré a echar un ojo.

2022-11-15 08:45 UTC, PabloGonzalezSegarra commented
Por cierto arregla el nombre del PR y el destino.
[NO MERGE] Fea...
ST-LIB_LOW <- features/Sensor

2022-11-16 10:34 UTC, ricardochust commented
he añadido un EncoderSensorWTime.cpp como una posible solución para el problema de velocidad y aceleración 0 por el exceso de velocidad del reloj. 

Básicamente cada frame_size segundos (o mas si el read se retrasa) guarda el contador del encoder, y va acumulando valores para calcular la velocidad. Luego la aceleración la calcula con la velocidad y la velocidad anterior. 

Otra opción seria el EncoderSensorWPosition, que trataría de almacenar los tiempos cada vez que cambia el contador del encoder, en lugar de almacenar el estado del contador cada frame de tiempo. Seria algo mas complejo de implementar, pero si  WTime no os convence puedo tratar de hacerlo.

2022-11-16 10:45 UTC, ricardochust commented
tratando el tema de la distancia relativa y el overflow, si el encoder sufre de overflow por restar cuando el contador esta a 0, ¿sigue funcionando usando el valor de overflow?, ósea ¿si esta en 0x0000.0000 y resta dos pasa a estar en 0xFFFF.FFFE?¿Y si le restara mas pasaría a 0xFFFF.FFFC? 
Lo digo porque puedo poner una solución usando complementarios 2, basado en la distancia de los nuevos valores respecto a los anteriores ya guardados bastante guay si es así. Si no es así necesitare poder reescribir el valor del contador del encoder o resetearlo y guardar un sumador para no perder precisión al resetear.

2022-11-16 10:57 UTC, PabloGonzalezSegarra commented
Con respecto a el _overflow_ se le dice _overflow_ cuando se supera la cantidad máxima de la variable, como el _CNT_ del _timer_ es un `uint32_t`(creo) es decir es positivo de 32 bits cuando llegue a `0xFFFFFFFF` y sume uno más el nuevo valor será `0x00000000` y si ocurre al contrario se le llama _underflow_ cuando el valor del _CNT_ es `0x00000000` y se resta 1 el nuevo valor será `0xFFFFFFFF`. En cuanto a como vas a conseguir obtener la posición en negativo lo mejor es que implementes lo que tengas pensado y cuando este avisa y le echamos un ojo. Ten en cuenta que quizás (no tengo ni idea) puedes usar en tu favor que el tubo va a tener un tamaño máximo por tanto si el tamaño máximo es 50 metros el _CNT_ como máximo podrá alcanzar el valor de 2000 (50m / 0.025m) hacia adelante y lo mismo restando 2000 a el valor máximo del tipo que devuelva el _CNT_.

2022-11-16 11:13 UTC, PabloGonzalezSegarra commented
Para el tema de evitar que nos de 0 cuando leemos demasiado rápido o el vehículo va lento (pero esta quieto) el año paso el primer _aproach_ fue simplemente meter una guarda en el _read_, si el valor del _CNT_ es igual al valor del anterior vez que hemos leído hacia `return`, es decir no calculaba. El problema de esta solución es que nunca da 0, es decir, no es capaz de detectar cuando esta quieto. Como había prisa lo que hice para intentar arreglarlo fue que si se leían valores de _CNT_ iguales seguidos durante `X` tiempo marcaba el 0. Esta solución aunque más o menos funcionaba no es una solución correcta, ni elegante, pues depende del valor de `X` si iba lento marcaba 0 sin estar quieto o si `X` era demasiado largo tardaba mucho en marcar 0 cuando ya estaba quieto. Te lo digo para que puedas partir de esa base.

2022-11-16 11:23 UTC, ricardochust commented
esa era la segunda opción, la implementación que mencionaba de EncoderSensorWPosition, que actualizaba cada vez que cambiaba el contador. El primer problema vendría a ser arreglar la reducción a 0, que lo haría guardando las ultimas veces que se ha movido y restando los tiempos con un diferencial de contador 1, hasta un mínimo que eligiéramos que si se comprometiera a ser velocidad 0.

La implementación que hice ahora es una basada en el tiempo, que encapsula en "Frames temporales" las distintas posiciones en las que ha estado el encoder. Al final el compromiso es el mismo, pues hay un mínimo de velocidad detectable dependiente de el tamaño de frames y la cantidad de frames que guardemos. Esta ya implementado en el EncoderWTime por si quieres echarle un ojo. No lo implemente directamente en el Encoder por si elegiamos la opcion de la posicion, que es la que hicisteis el año pasado (pero tratando de mejorarla claro)

2022-11-21 22:40 UTC, alejandrogonzalvo requested changes
Revisa todos los problemas de inconsistencia que no te he marcado y traduce comentarios al ingles, intenta que sean breves pero explicativos. Si no aportan nada quitalos, el codigo es bastante legible.

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +	uint8_t getID();
```suggestion
	uint8_t get_id();
```
las funciones en snake_case, revisa todo y cambia las que hagan falta

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.hpp
> +	void exti_interruption(std::function<auto> lambda);
```suggestion
	void exti_interruption(std::function<auto> action);
```
usa nombres explicativos, es una accion no? si no, ponle el nombre que tu veas que explica mejor lo que representa.

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
> +#define clock_frequency 300000000
```suggestion
#define CLOCK_FREQUENCY 300000000
```
constantes en mayuscula

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +		//TODO: errores de optional vacio aqui (por hacer)
```suggestion
		//TODO: empty optional error handle 
```
pon los comentarios en ingles. Estos no son tan importantes porque luego los quitaremos pero el resto los vera todo el mundo que quiera usar nuestro codigo

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensorWTime.cpp
> +			if(counter - counters[n_frames-1] > 0xEFFFFFFF){
Que representa 0xEFFFFFFF? Quizas iria mejor una constante

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensorWTime.cpp
> +		*acceleration = (*speed - last_speed) * clock_frequency * (n_frames-1) / (delta_time); //usa solo 1 frame (y el anterior) para el calculo
```suggestion
		*position= ((double) counters[n_frames-1]) * counter_distance;
		*speed = abs(*position - last_position) * clock_frequency / (delta_time); 
		*acceleration = (*speed - last_speed) * clock_frequency * (n_frames-1) / (delta_time); 
```
Aqui sobran las whitelines y los comentarios no aportan información. Intenta que los comentarios realmente aporten información extra, ademas en este me gusta mucho el cálculo, creo que es muy legible y no hace falta poner nada

2022-11-21 22:40 UTC, alejandrogonzalvo commented on Src/ST-LIB_LOW/Sensors/LinearSensor/LinearSensor.cpp
> +	}else{
```suggestion
	}
	else {
```
Se consistente con el formato

2022-11-22 21:20 UTC, PabloGonzalezSegarra commented
Ricardo ya se que aun estas trabajando en la rama pero mira a ver como arreglas el hecho de que has modificado 28 archivos. Hazle merge de HALAL a ST-LIB_LOW para que no salga asi.

2022-11-22 21:21 UTC, PabloGonzalezSegarra commented
Y aunque ahora ya esta deberias haber hecho cada sensor en un rama distinta poco a poco. Para la próxima tenlo en cuenta. Cuanto más pequeñas las ramas mejor y aunque realentice un poco el desarrollo vale la pena tener código de más cálidad.

2022-11-22 22:13 UTC, ricardochust commented
> Ricardo ya se que aun estas trabajando en la rama pero mira a ver como arreglas el hecho de que has modificado 28 archivos. Hazle merge de HALAL a ST-LIB_LOW para que no salga asi.

lo he intentado pero esta bloqueada como la HALAL o la main. Tendria que hacer un pull request si eso. Bueno creo que esta bloqueada porque me da un error al mergear, mañana escribo aqui el error que me sale.

2022-11-22 22:14 UTC, ricardochust commented
> Y aunque ahora ya esta deberias haber hecho cada sensor en un rama distinta poco a poco. Para la próxima tenlo en cuenta. Cuanto más pequeñas las ramas mejor y aunque realentice un poco el desarrollo vale la pena tener código de más cálidad.

Lo se, ya me lo comento Stefan. Fue un poco desastre la verdad pero aun me estaba aclarando con el github.

2022-11-22 22:20 UTC, ricardochust commented
> > Ricardo ya se que aun estas trabajando en la rama pero mira a ver como arreglas el hecho de que has modificado 28 archivos. Hazle merge de HALAL a ST-LIB_LOW para que no salga asi.
> 
> lo he intentado pero esta bloqueada como la HALAL o la main. Tendria que hacer un pull request si eso. Bueno creo que esta bloqueada porque me da un error al mergear, mañana escribo aqui el error que me sale.

Como pequeño añadido también estoy usando varios archivos que aun están en pull-request, como el time y el ADC actualizado. Esos seguirán apareciendo como modificados hasta que se completen y se añadan a la HALAL (aparte de que pueda hacer el merge)

2022-11-23 07:56 UTC, PabloGonzalezSegarra commented
Si no te deja habla con estefan para que quite el bloqueo un segundo y puedas hacer el merge.

2022-11-24 14:53 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
> +		//TODO: errores de optional vacio aqui (por hacer)
Cuando pones `//TODO: ` ya se entiende que esta por hacer y haz los comentarios de este tipo en ingles.

2022-11-24 14:53 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
> +//digitalInput doesn t return an optional in register. Instead, it returns the value directly (fault free?)
Si esto es un probelma (nose a que te refieres asi que no lo se) abre una issue

2022-11-24 14:54 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/LinearSensor/LinearSensor.cpp
> +	}else{
Como esta esta bien

2022-11-24 15:15 UTC, ricardochust commented on Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
> +//digitalInput doesn t return an optional in register. Instead, it returns the value directly (fault free?)
era mas una duda, pero se puede dejar asi. Es que digitalInput a diferencia de las otras clases que uso no retorna un optional que envuelve el valor, si no que devuelve el valor directamente sin envoltorio, lo cual me hace pensar que no pueda haber fallo al registrarlo. Era curiosidad de porque era distinto, pero si no hay posibilidad de que falle al registrar se puede quedar asi perfectamente

2022-11-24 15:16 UTC, ricardochust commented on Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
> +		//TODO: errores de optional vacio aqui (por hacer)
Ese comentario tengo que actualizarlo. Ahora reviso todos los comentarios que estan hechos un poco un desastre.

2022-11-24 15:25 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
> +//digitalInput doesn t return an optional in register. Instead, it returns the value directly (fault free?)
Lo hablamos mañana en la reunion, apuntatelo.

2022-11-25 15:36 UTC, closed without merging