[FW-59]
HyperloopUPV-H8/ST-LIB pull request #424
Opened 2024-10-23 11:30 UTC by jdmarmen

Modified the DualPWM .cpp and .hpp so as to be used with the HALAL mock.  

- Created a bool is_on for each positive and negative channel, at the moment, that is the only variable that should be independent for each channel. Duty, freq and dead_time should be the same in both, so in the constructor, those instance variables point only to the pin_positive address memory, then the pin_negative copies the values.

Also added a DualPWM PinType and defined its struct at Pin.hpp.

2024-10-23 13:17 UTC, jmaralo requested changes
don't abbreviate function parameter names, they help later on decipher what each parameter is, the units it has and gives more information to the user. Trying to remember all the units and what every parameter is can be hard and long descriptive names help.

2024-10-23 13:17 UTC, jmaralo commented on Inc/HALALMock/Services/PWM/DualPWM/DualPWM.hpp
> +	DualPWM(Pin& pin_pos, Pin& pin_neg);
why the change in the name?

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +		if(pin_positive.type==PinType::NOT_USED)
redundant if, already being checked in the previous condition

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +		if(pin_negative.type==PinType::NOT_USED)
same as before, this is already checked before

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +	*negative_is_on=false;
this is only relative to the positive, no need to change the negative

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +  	*positive_is_on=false;
this is only relative to the negative, no need to change the positive

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +	*(this->duty_cycle) = dc;
```suggestion
void DualPWM::set_duty_cycle(float duty_cycle){
	*(this->duty_cycle) = duty_cycle;
```

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +  	*(this->frequency) = freq;
```suggestion
void DualPWM::set_frequency(uint32_t freq_in_hz){
  	*(this->frequency) = freq_in_hz;
```

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +void DualPWM::set_dead_time(std::chrono::nanoseconds dead_t_ns)
```suggestion
void DualPWM::set_dead_time(std::chrono::nanoseconds dead_time_ns)
```

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +	*(this->dead_time_ns)=dead_t_ns;
```suggestion
	*(this->dead_time_ns)=dead_time_ns;
```

2024-10-23 13:17 UTC, jmaralo commented on Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
> +	*/
```suggestion
```

2024-10-23 13:17 UTC, jmaralo commented on Inc/HALALMock/Services/PWM/DualPWM/DualPWM.hpp
> +	DualPWM(Pin& pin_pos, Pin& pin_neg);
If you want to go with this I would call them `pin_positive` and `pin_negative` and give a new name to the EmulatedPins

2024-10-23 18:59 UTC, jmaralo approved these changes
LGTM

2024-10-24 23:03 UTC, g0nz4I0 approved these changes

2024-10-25 15:10 UTC, merged