New implementation for the ringBuffer by index
HyperloopUPV-H8/ST-LIB pull request #431
Opened 2024-10-26 15:31 UTC by Ikubimu

2024-10-26 17:28 UTC, jmaralo reviewed
Please add a description in your PRs, is useful when reviewing and to warn about certain known bugs or issues

2024-10-26 18:00 UTC, jmaralo approved these changes
Looks good, but there is already a half working implementation of a ring buffer in `Inc/C++Utilities/RingBuffer.hpp`, the idea was to fix that implementation, but if this works I won't complain (at least not until we need to use another ring buffer other than this :))

2024-10-26 19:32 UTC, Ikubimu commented
Ok I didnt know, I ll take a look at

2024-10-27 15:26 UTC, g0nz4I0 requested changes
Looks good, but could you move the implementation to the existing RingBuffer to replace it? Is is in  `Inc/C++Utilities/RingBuffer.hpp`, also this way we can test it more easily

2024-10-27 15:27 UTC, g0nz4I0 commented on Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
> +: position(position), direction(direction), speed(speed), acceleration(acceleration), idx_buff(0){
TIP: when you declare it in the class you can do: `uint32_t idx_buff{0};` and that will initialize it, without having to explicitly list it out in the constructor

2024-10-27 19:29 UTC, Ikubimu commented
Just  a thing, the actual RingBuffer implementation manage the buffer as a consumer-producer , this means that can't overwrite on the buffer. It doesn't make sense to me because the speetech is continuously reading data. Should a new template model be done to implement that way or something?

2024-10-27 19:36 UTC, g0nz4I0 commented
What do you mean as a consumer-producer, I see that push fails if its full, therefore you should call `pop` before, but feel free to reimplement it

2024-10-27 20:03 UTC, Ikubimu commented
Encoder sensor obtains the last measure by pointer, then doesn't care the about the buffer. And the buffer fails if is full, then it would be all the time pop and push and I see innecesary

2024-10-27 20:08 UTC, Ikubimu commented
If Encoder is always measuring,  shouldn't it be able to update the buffer ignoring if is full or not?

2024-10-31 17:16 UTC, jmaralo approved these changes

2024-11-06 21:00 UTC, g0nz4I0 approved these changes
Easy way of seeing if it works, if it doesnt we just revert

2024-11-06 21:00 UTC, merged