[FW-98] PWM Tests
HyperloopUPV-H8/ST-LIB pull request #462
Opened 2024-11-19 02:55 UTC by jdmarmen

- Small changes in set_dead_time to ensure that we can only set the dead_time if the PWM is off.
- Added PWM tests

2024-11-19 09:02 UTC, gonzalo-sm approved these changes
Doesn't this trigger an ErrorHandler? because I dont see a pin map in this PR defining the map with `available_pwms`

2024-11-19 09:04 UTC, gonzalo-sm requested changes
I'm disapproving it, Check ErrorHandler is not triggered

2024-11-20 12:13 UTC, gonzalo-sm commented
Add the checks to ErrorHandler in the implementation of the class, both in PWM and DualPWM, then check that ErrorHandler is not triggered in the test.

2024-11-20 22:00 UTC, g0nz4I0 approved these changes

2024-11-20 22:12 UTC, Ikubimu approved these changes

2024-11-20 22:12 UTC, merged