[FW-99] DualPWM Tests
HyperloopUPV-H8/ST-LIB pull request #463
Opened 2024-11-19 03:00 UTC by jdmarmen

- Modified DualPWM structure for accessing emulated pin variables, now the Emulated Pins are instance members and get initialized in the constructor to modify their variable values when calling set_duty_cycle(), set_frequency() and set_dead_time(). In the old version, we were only able to modify the positive pin value, the negative one could only be accessed in the constructor.
- Added DualPWM tests.

2024-11-19 09:04 UTC, gonzalo-sm requested changes
Same as in the other PR, this test should actually fail, because an ErrorHandler will be triggered

2024-11-21 17:01 UTC, Ikubimu approved these changes
It's seems good

2024-11-22 14:36 UTC, g0nz4I0 requested changes
Remove the ErrorHandlerTriggered check in all the functions, we only want the check inside the test, not in the library function

2024-11-22 15:06 UTC, g0nz4I0 approved these changes

2024-11-22 15:06 UTC, merged