[FW-126] Use Logger
HyperloopUPV-H8/ST-LIB pull request #478
Opened 2024-12-26 19:28 UTC by jorgesg82

It has been modified some mocks to use the new Logger instead of using ErrorHandler/cout. Also the linter has been applied on some sources.

2024-12-28 15:01 UTC, jmaralo approved these changes
Linter go brrrr

2025-01-09 12:24 UTC, oganigl requested changes

2025-01-09 12:24 UTC, oganigl commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +}
I don't understand why every file change the look for example in this case was like this: Socket::~Socket(){
	auto it = std::find(OrderProtocol::sockets.begin(), OrderProtocol::sockets.end(), this);
	if(it == OrderProtocol::sockets.end()) return;
	else OrderProtocol::sockets.erase(it);
	close();
}more compact and better than the new one

2025-01-09 12:24 UTC, oganigl commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +    state = CLOSING;
could be a good idea add a LOG_INFO when the socket is closed
```suggestion
    state = CLOSING;
    LOG_INFO("Socket has been closed correctly")
```

2025-01-09 12:24 UTC, oganigl commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +void Socket::reconnect() {  // I'm going to do in reconnect a total reset due to
Look this case, I don't know if it's only in github  but for a function of 1 line now there are 3 lines

2025-01-19 00:35 UTC, g0nz4I0 commented on Src/HALALMock/Services/Communication/Ethernet/Ethernet.cpp
> +        LOG_INFO("Ethernet started succesfully");
I dont understand this comment

2025-01-19 00:37 UTC, g0nz4I0 commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +unordered_map<EthernetNode, Socket*> Socket::connecting_sockets = {};
yes, @jorgesg82 fix this one

2025-01-19 00:38 UTC, g0nz4I0 commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +}
nitpick, dont worry about it, we should get the same linter for everybody, also next time learn how to format code inside a comment 😜

2025-01-19 00:39 UTC, g0nz4I0 commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +void Socket::reconnect() {  // I'm going to do in reconnect a total reset due to
linter again

2025-01-19 00:40 UTC, g0nz4I0 commented on Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
> +unordered_map<EthernetNode, Socket*> Socket::connecting_sockets = {};
```suggestion
```

2025-01-19 00:41 UTC, g0nz4I0 approved these changes

2025-01-19 00:46 UTC, merged