Features/state machine
HyperloopUPV-H8/ST-LIB pull request #61
Opened 2022-11-28 17:28 UTC by alejandrogonzalvo

# 😎 State Machine 😎 
This commit implements the State Machine class for the ST-LIB LOW.

### Usage:
```
/* USER CODE BEGIN PV */
enum states : uint8_t {
	off = 0,
	on = 1,
	sleep = 2,
	fault = 3
};

StateMachine state_machine;
float adc_value;

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  uint8_t adc1 = ADC::inscribe(PF11).value();
  uint8_t exti1 = ExternalInterrupt::inscribe(PE0, [&]() {
	  if (state_machine.current_state == off) {
		  state_machine.change_state(on);
	  }
	  else {
		  state_machine.change_state(on);
	  }

  }).value();

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

/* Configure the peripherals common clocks */
  PeriphCommonClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_ETH_Init();
  ADC::start();
  MX_FDCAN1_Init();
  MX_TIM1_Init();
  MX_TIM3_Init();
  MX_TIM4_Init();
  MX_TIM8_Init();
  MX_TIM12_Init();
  MX_TIM23_Init();
  MX_USART1_UART_Init();
  MX_USART2_UART_Init();
  MX_CORDIC_Init();
  MX_FMAC_Init();
  MX_RTC_Init();
  MX_TIM15_Init();
  MX_TIM16_Init();
  MX_LPTIM1_Init();
  MX_LPTIM3_Init();
  MX_SPI3_Init();
  MX_TIM17_Init();
  MX_FDCAN3_Init();
  MX_LPTIM2_Init();
  /* USER CODE BEGIN 2 */
  Time::start();
  uint8_t timer1 = Time::register_low_precision_alarm(10, [&]() {
	  state_machine.update();
  });

  state_machine = StateMachine(off);
  state_machine.add_state(on);
  state_machine.add_state(sleep);
  state_machine.add_state(fault);

  state_machine.add_enter_action(off, on, [&]() {
	  ADC::turn_on(adc1);
  });
  state_machine.add_update_action([&]() {
	  adc_value = ADC::get_value(adc1).value();
  }, on);

  /* USER CODE END 2 */

  while (1) {}
}
```

2022-11-29 23:55 UTC, StefanCostea approved these changes

2022-12-02 19:37 UTC, PabloGonzalezSegarra requested changes

2022-12-02 19:49 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	map<uint8_t, map<uint8_t, vector<function<void()>>>> on_enter;
acciones*

2022-12-06 19:17 UTC, PabloGonzalezSegarra approved these changes
En general me gusta. Cambia lo que te he puesto. Suponiendo como siempre que has pasado los tests suficientes te lo apruebo.

2022-12-06 19:17 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
> +	map<uint8_t, State> states;
Usa unordered map mejor.

2022-12-06 19:17 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
> +	if (not current_state) {
Este if creo que está mal. Si el estado actual en tu ejemplo fuese off y añadieses una acción daría error. Deberías comprobar que no esté vacío el mapa de Estados.

2022-12-08 09:53 UTC, merged