Features/pwm start
HyperloopUPV-H8/ST-LIB pull request #63
Opened 2022-11-29 10:09 UTC by alejandrogonzalvo

# PWM start function
This PR implements the start function for the PWM service that substitutes HAL MX_tim_init().

### Before
```
  Pin::start();
  MX_TIM1_Init();
  MX_TIM15_Init();
  MX_TIM16_Init();
  PWM::turn_on(pwm1);
  PWM::set_duty_cycle(pwm1, 50);
```

### After
```
  Pin::start();
  PWM::start();
  PWM::turn_on(pwm1);
  PWM::set_duty_cycle(pwm1, 50);
```

It has been tested with the analog device that the behaviour is the same as with the HAL function

2022-11-29 13:23 UTC, StefanCostea approved these changes

2022-11-29 13:23 UTC, StefanCostea commented on Inc/HALAL/Services/PWM/PWM.hpp
> +	public:
structs are public by default

2022-11-29 13:23 UTC, StefanCostea commented on Inc/HALAL/Services/PWM/PWM.hpp
> +		dual = 2
use caps in enums

2022-11-29 13:25 UTC, StefanCostea requested changes
Accepted by mistake

2022-11-29 15:01 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/PWM/PWM.hpp
> +		dual = 2
like Normal or NORMAL?

2022-11-30 12:18 UTC, PabloGonzalezSegarra requested changes
Revisa lo que te he puesto, en general esta bien.

2022-11-30 12:18 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PWM.cpp
> +	if (not available_instances.contains(pin)) {
Deja el `PWM::` delante de los metodos y atributos de la clase PWM que lo deja mucho más claro.

2022-11-30 12:18 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PWM.cpp
> +	if (not available_instances.contains(pin)) {
Esto en todos lados.

2022-11-30 12:18 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PWM.cpp
No dejes espacios entre los if.

2022-11-30 12:18 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWM/PWM.cpp
> +		//TODO: error handle
Nose porque le estas quitanod las r, pero es con r. Vuelveselas a poner xD. El TODO indica que ahi va la funcion error handler no que haya que handlear el error que son cosas distintas. Error handler es nuestro error handler que manda el mensaje del error y entra en un bucle. Poner error handle significa que hay que handlearlo de alguna manera pero no esta definida que no es el caso.

2022-11-30 14:46 UTC, StefanCostea approved these changes

2022-11-30 15:50 UTC, PabloGonzalezSegarra approved these changes

2022-11-30 17:20 UTC, merged