Features/uart
HyperloopUPV-H8/ST-LIB pull request #65
Opened 2022-11-30 10:56 UTC by PabloGonzalezSegarra

# UART service Pull Request

## Service description

La interfaz del servicio es exactamente igual a la del SPI, es decir registras un UART y posteriormente envias o recibes mensajes con los respectivos metodos. 
Para mandar un packet, que deben ser RawPacket como el SPI, se utiliza el siguiente metodo:
```cpp
bool UART::transmit_next_packet(uint8_t id, RawPacket& packet)
```

Al igual que el SPI los mensajes se mandan y reciben por DMA, por tanto tras enviar un mensaje deberemos comprobar que este ya se ha enviado antes de mandar esto. Para comprobar que no esta ocupado usamos el siguiente metodo:
```cpp
bool UART::is_busy(uint8_t id)
```

Para recibir un paquete utilizaremos el siguiente metodo:
```cpp
bool UART::receive_next_packet(uint8_t id, RawPacket& packet)
```
Analogamente a enviar paquetes, cuando queremos recibir uno debemos asegurarnos que el el paquete esta listo para ser usado con el siguiente metodo:
```cpp
bool UART::has_next_packet(uint8_t id)
```

## UART documentation

- [x] El UART ha sido completamente documentado usando doxygen igual que el SPI.

## UART Error handling

- [x] El UART tiene TODO: para handlear errores como el resto de servicios a la espera de la implementación del error handler.
- [x] El UART al igual que el SPI tiene implementado el callback de error del periferico con un TODO: a la espera de decidir como handlear este error, lo mas sensato seria mandar a fault.

## Testing

El testeo de este servicio se ha hecho igual que el del SPI, con la excepcion que en este caso ha sido más sencillo al poder ver los mensajes UART directamente por  consola en el STM32CubeIDE.
A continuación se puede ver uno de los código que se uso para el testo:
```cpp
  /* USER CODE BEGIN 2 */
  HAL_GPIO_TogglePin(LED_YELLOW_GPIO_Port, LED_YELLOW_Pin);

  uint8_t id = UART::inscribe(UART::uart3);
  uint32_t data = 0;
  RawPacket packet = RawPacket(&data);
  /* USER CODE END 2 */
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
	  UART::receive_next_packet(id, packet);

	  while(!UART::has_next_packet(id)){
	  }

	  if (*packet.get_data() == 'a') {
		HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_SET);
	  }else{
		HAL_GPIO_WritePin(LED_RED_GPIO_Port, LED_RED_Pin, GPIO_PIN_SET);
	  }

	  UART::transmit_next_packet(id, packet);
	  while(UART::is_busy(id)){
	  }

    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
```

2022-11-30 11:10 UTC, alejandrogonzalvo requested changes
Revisa identación y llaves en los if y cambia el switch

2022-11-30 11:10 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +                               };
```suggestion
 };
```

2022-11-30 11:10 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +    }
```suggestion
	UART::Instance*	uart_instance;

    switch(uart){
        case UART::Peripheral::peripheral3:
        uart_instance = &UART::instance3;
        break;
    }
```
Esto en vez de con un switch seria mejor con un mapa de periferico a instancia, mas coherente con el resto de perífericos, es generable con el runes y no tienes que cambiar al funcion cuando añades un periferico.

2022-11-30 11:10 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +        return false; //TODO: Error handler
```suggestion
    if (not UART::registered_uart.contains(id)) {
        return false; //TODO: Error handler
    }
```

2022-11-30 12:02 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +                               };
Ni caso a la identación. Se ve mal en el Github porque el cube usa tabulaciones para las identaciones en vez de espacios y cada editor los interpreta de una manera. En el cube los tabs ocupan 4 espacios mientras que en github es un numero distinto. Es decir que en el cube se vera bien.
Molaria que todos configuraramos el cube para que identara con espacios que se ven igual en todos los editores. Le pasare una extension que tengo en el visual que ten cambia todo a espacios para que se vea bien aunque en github.

2022-11-30 14:55 UTC, StefanCostea approved these changes

2022-11-30 14:55 UTC, StefanCostea commented on Src/HALAL/Services/Communication/UART/UART.cpp
> +    auto* uart = UART::registered_uart[id];
Don't use auto if it is not needed

2022-12-02 20:12 UTC, alejandrogonzalvo requested changes

2022-12-02 20:12 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
>  uint8_t UART::inscribe(UART::Peripheral& uart){
porque no empiezas en cero y devuelves un optional como el resto de perifericos?

2022-12-04 13:53 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Communication/UART/UART.cpp
>  uint8_t UART::inscribe(UART::Peripheral& uart){
Porque me estoy dando cuenta que es una abstracción que sobra. Es más óptimo en este caso usar el 0 por ahora hasta el rework. Mi idea es cambiar el tema de los optionals. En la reunión lo comentaré.

2022-12-05 13:12 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Communication/UART/UART.cpp
>  uint8_t UART::inscribe(UART::Peripheral& uart){
vale

2022-12-05 13:21 UTC, alejandrogonzalvo approved these changes

2022-12-05 13:30 UTC, merged