Half Bridge
HyperloopUPV-H8/ST-LIB pull request #74
Opened 2022-12-02 21:40 UTC by alejandrogonzalvo

# Half Bridge
This Pull Request implements the Half Bridge class, which controls Half bridge circuits using PWM and an enable pin controlled by a DigitalOutput. 

### Usage:
``` cpp
/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "ST-LIB.hpp"

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

/* Configure the peripherals common clocks */
  PeriphCommonClock_Config();

  HalfBridge half_bridge1 = HalfBridge(PE9, PE8, PE11, PE10, PE15);

  Pin::start();
  PWMservice::start();

  half_bridge1.turn_on();

  while (1)
  {
	  half_bridge1.set_duty_cycle(30);
	  HAL_Delay(1000);
	  half_bridge1.set_duty_cycle(-30);
	  HAL_Delay(1000);
  }
}
```

### Implementation:
_**Problem:** You can implement negated pwm by firmware or hardware._
_**Solution:** We use an overloaded constructor for distinction between the two cases, and then it is handled internally by the services_
```cpp
HalfBridge(Pin& positive_voltage_pwm_pin, Pin& negative_voltage_pwm_pin, Pin& enable_pin);

HalfBridge(Pin& positive_voltage_pwm_pin, Pin& positive_voltage_pwm_negated_pin, Pin& negative_voltage_pwm_pin, Pin& negative_voltage_pwm_negated_pin,
			Pin& enable_pin);
```

### Testing:
_To do:_

2022-12-06 19:18 UTC, PabloGonzalezSegarra commented
Me gusta que hayas añadido para descargar tu test.

2022-12-06 19:23 UTC, PabloGonzalezSegarra requested changes
Miras las cositas que te he puesto. En general bien.

2022-12-06 19:23 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.hpp
> +	HalfBridge(Pin& positive_voltage_pwm_pin, Pin& positive_voltage_pwm_negated_pin, Pin& negative_voltage_pwm_pin, Pin& negative_voltage_pwm_negated_pin,
Aquí te puedes ahorrar el voltage para que no se haga tan largo.

2022-12-06 19:23 UTC, PabloGonzalezSegarra commented on Inc/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.hpp
> +	PWM negative_voltage_pwm;
Quedamos que usarías el servicio directamente.

2022-12-06 19:23 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/PWMservice/PWMservice.cpp
> +PWMservice::TimerInitData::TimerInitData(TIM_TypeDef* timer, uint32_t prescaler, uint32_t period, uint32_t deadtime) :
[No tiene nada que ver con esta linea] Ya que estas podrías cambiar el id mànager como quedamos. Tienes un ejemplo en mis PR de los inits.

2022-12-06 19:23 UTC, PabloGonzalezSegarra commented on Src/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.cpp
> +	enable.turn_on(); // enable al final para evitar ruido
Estos comentarios recuerda ponerlos en la docu y en inglés. Docu que podrías hacer ya 😉.

2022-12-07 12:26 UTC, StefanCostea commented on Inc/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.hpp
> +	PWM negative_voltage_pwm;
eso importante si

2022-12-07 12:28 UTC, StefanCostea requested changes

2022-12-07 12:28 UTC, StefanCostea commented on Src/HALAL/Models/PinModel/Pin.cpp
> +			GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
revisa si las pwm a altas frecuencias mejoran poniendo el speed en VERY HIGH

2022-12-07 12:29 UTC, StefanCostea commented on Src/HALAL/Models/PinModel/Pin.cpp
> +			GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
a ver si la señal es mas limpia

2022-12-08 10:11 UTC, alejandrogonzalvo commented on Src/HALAL/Services/PWMservice/PWMservice.cpp
> +PWMservice::TimerInitData::TimerInitData(TIM_TypeDef* timer, uint32_t prescaler, uint32_t period, uint32_t deadtime) :
habria que hacerlo en un pr a parte, esto  no se va a mergear a HALAL sino a STLIB-LOW

2022-12-09 18:19 UTC, PabloGonzalezSegarra reviewed
Documenta.

2022-12-09 18:19 UTC, PabloGonzalezSegarra approved these changes
Documenta.

2022-12-10 12:08 UTC, StefanCostea approved these changes

2022-12-10 12:36 UTC, merged