Timer Peripheral model and HALAL hotfix round
HyperloopUPV-H8/ST-LIB pull request #80
Opened 2022-12-09 08:45 UTC by alejandrogonzalvo

# Timer Peripheral
This PR implements the timer peripheral model and some general changes for HALAL  (check diff).

### Usage:
_Lacks testcase_

### Implementation:
The model has a static list of timers that can be accessed by the services, 
```cpp
static vector<reference_wrapper<TimerPeripheral>> timers;
```

so they are configured when inscribed.
```cpp
optional<uint8_t> PWMservice::inscribe(Pin& pin){

       \\ ...

	Pin::inscribe(pin, ALTERNATIVE);

	TimerPeripheral::InitData& init_data = active_instances[id].peripheral->init_data;
	init_data.pwm_channels.push_back(active_instances[id].channel);
	return id;
```
Then when you call `TimerPeripheral::start`, it loops through all timers and checks which ones are used.
```cpp
void TimerPeripheral::start() {
	for (TimerPeripheral timer : timers) {
		if (timer.is_registered()) {
			timer.init();
		}
	}
}
```

### Testing:
It has been tested to work on NORMAL and DUAL pwm.

## Hotfixes

- Simplify pin enums.
- Simplify id_manager 
- Fix incoherent naming conventions in digital output and pin enums

2022-12-10 12:20 UTC, StefanCostea requested changes

2022-12-10 12:20 UTC, StefanCostea commented on Inc/HALAL/Models/PinModel/Pin.hpp
> +	PORT_H = DOMAIN3_ADVANCED_HIGH_PERFORMANCE_BUS1 + 0x1C00UL,
aqui no simplificas nada xd haces todo lo contrario metes un define que no se entiende que es y un puñado de magic numbers pero bueno

2022-12-10 12:20 UTC, StefanCostea commented on Inc/HALAL/Models/PinModel/Pin.hpp
> +	ALTERNATE_FUNCTION,
Lo dicho no tengas alternative y alternative function supuestamente codificaban para lo mismo si ahora quieres separarlos ponle un nombre identificativo

2022-12-10 12:20 UTC, StefanCostea commented on Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
> +};
mucho mas limpio y logico esto que lo que habia antes

2022-12-10 12:41 UTC, alejandrogonzalvo commented on Inc/HALAL/Models/PinModel/Pin.hpp
> +	PORT_H = DOMAIN3_ADVANCED_HIGH_PERFORMANCE_BUS1 + 0x1C00UL,
Claro que si, los magic numbers eran las dos cifras que habias puesto sumadas antes, ahora se entiende  que es la direccion de memoria del AHB del D3 de la RAM mas el offset correspondiente de cada pin. En el hipotetico caso de que  el siguiente programador que lea el codigo no sepa lo que es, puede pegar el nombre de la constante y investigar en internet lo que son los domains de la ram o el high performance bus

2022-12-11 20:16 UTC, StefanCostea commented on Inc/HALAL/Models/PinModel/Pin.hpp
> +	PORT_H = DOMAIN3_ADVANCED_HIGH_PERFORMANCE_BUS1 + 0x1C00UL,
vale bro pero literalmente estaban ahi porque los mockups no tienen la hal y no pueden acceder a esa constante xd

2022-12-11 20:18 UTC, StefanCostea commented on Inc/HALAL/Models/PinModel/Pin.hpp
> +	PORT_H = DOMAIN3_ADVANCED_HIGH_PERFORMANCE_BUS1 + 0x1C00UL,
vuelve a dejarlo como estaba

2022-12-12 15:09 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Models/PinModel/Pin.hpp
> +	PORT_H = DOMAIN3_ADVANCED_HIGH_PERFORMANCE_BUS1 + 0x1C00UL,
Aunque pueden seguir siendo #defines

2022-12-12 15:14 UTC, PabloGonzalezSegarra reviewed
En general bien.

2022-12-12 15:14 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/PinModel/Pin.cpp
> +		{}
Para hacerlo asi porque no hacerlo de forma clasica dentro de las llaves?

2022-12-12 15:14 UTC, PabloGonzalezSegarra commented on Src/HALAL/Models/PinModel/Pin.cpp
> +Pin PE1(PORT_E, PIN_1);
Cual es el criterio para tener algunos pines con funcion alternativa y otros sin?

2022-12-12 15:20 UTC, alejandrogonzalvo commented on Src/HALAL/Models/PinModel/Pin.cpp
> +Pin PE1(PORT_E, PIN_1);
Los que gastan AF son los que la necesitan en el init

2022-12-12 15:20 UTC, alejandrogonzalvo commented on Src/HALAL/Models/PinModel/Pin.cpp
> +		{}
Por consistencia con el resto de cosas

2022-12-12 16:06 UTC, StefanCostea approved these changes

2022-12-12 18:36 UTC, PabloGonzalezSegarra requested changes
¿Y los tests?

2022-12-12 18:37 UTC, PabloGonzalezSegarra approved these changes
![image](https://user-images.githubusercontent.com/58437819/207127021-dbb6561f-0fef-4588-946b-b0b729f4500d.png)
Teniendo en cuenta que esto tiene que ser movido a Runes y ser autogerado. Y suponiendo que los tests que has mencionado son de verdad te lo apruebo.

2022-12-12 19:26 UTC, merged