Features/cordic
HyperloopUPV-H8/ST-LIB pull request #81
Opened 2022-12-09 17:32 UTC by ricardochust

CORDIC class done and tested

The class works in a very simple way, it doesn t even need any start method. If you want a sine, you just use the sine method and it does all the magic alone.
First it checks if its properly configurated, and if its not then configurates it. After that, the method just feeds the CORDIC until it has no more values to calculate on the in pointers, and fills the out pointers with the results. 

The calculations all work with int values, which represent different things for each method. It uses its own units, but if we work with these units on all calculations there shouldn t be any problem.

The units work as follows:

- angle: the max int value (2147483647) represents 180 degrees, or pi radians. After that it just wraps into the negatives. It seems like that would be troublesome, but it is made so overflow and underflow work on our favour, as if we add 2º to 180º we still get 182º (as it overflows to -2123622718, which represents 182º). In uint logic it is just 360 positive degrees no problem. 

- distances: very simple, from a point of reference, 2147483647 is the maximun positive and -2147483647 is the maximun negative. Point. Using very low values (like 15 000) may give less precise results, so do not fear using reasonably high numbers. In uint logic when we get over the maximun value it just appears on the other side, so beware with overflows on these units. 
 
- cos and sine results: as simple as distances. 2147483647 is one (the max value possible) and -2147483647 is minus one (the minimun value possible). Very simple. 

The tests were quite rudimentary, just testing some values on the correct units, calculated them 5 000 000 times and see how much times they take and if they were correct. Some values tested were 0, pi/3, pi/2, pi -pi/2 for cosine and sine and (1 0) (1 1) (0 1) (0.3 1) (-1 0) (-0.5 -1) for the modulus and phase (traduced to ints and put against arm.math with ints when possible).
They seemed to be at least twice as fast as arm.math and also have the advantage to be able to calculate sines and cosines or modulus and phase in just one take (which makes it potentially 4 times as fast)

If we wanted even more speed we could reduce the precision quite easily by changing the configuration step inside of each method. I though on doing a variable for precision to make it even easier to change, but it would need an OR calculation on each configuration and it is not like we are going to change that each week.

At last, the methods can work just as good with only one input on the pointers, you just need to make the size parameter one. If you will do multiple calculations it is obviously better to give all of them at once, but you just lose 2 comparations and one jump so its not gonna explode. You can even give a pointer to a 1000 matrix and tell it to just use the first 100, just put the size parameter to 100 and it will use the 100 first and then stop. (disclaimer: it wouldn t work if you give 100 matrix and put a 1000 in the size parameter, don t do that, it will go out of the pointer)

2022-12-09 18:12 UTC, PabloGonzalezSegarra requested changes
Review mia y de Stefan.

2022-12-09 18:12 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/CORDIC/CORDIC.hpp
> +	enum Operation_Computation{
Porque este enum esta identado?

2022-12-09 18:12 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/CORDIC/CORDIC.hpp
> +	static Operation_Computation mode;
Los atributos primero que los metodos.

2022-12-09 18:12 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/CORDIC/CORDIC.cpp
> +void RotationComputer::cos(int32_t *angle, int32_t *out, int size){
Intenta usar `int32_t` en vez de `int` normal. Si no sabes que tamaño quieres puedes usar `size_t`.

2022-12-09 18:12 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/CORDIC/CORDIC.cpp
> +		for(int n = 0; n < size; n++){
Porque este for esta identado?

2022-12-09 18:12 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/CORDIC/CORDIC.cpp
> +}
Tienes que documentar muy bien con doxygen la clase. Una entrada en la wiki tampoco estaria mal. Es muy dificil entender el código. Además como he puesto antes usa #define para los numeros mágicos y explicalos.

2022-12-13 14:14 UTC, PabloGonzalezSegarra commented on Inc/HALAL/Services/CORDIC/CORDIC.hpp
> +	 * the modulus function is a bit more fragile than the other functions.
Empieza las frases en mayusculas.

2022-12-13 14:15 UTC, PabloGonzalezSegarra approved these changes

2022-12-13 14:24 UTC, StefanCostea approved these changes

2022-12-13 14:24 UTC, merged