Features/encoder init
HyperloopUPV-H8/ST-LIB pull request #82
Opened 2022-12-10 09:00 UTC by PabloGonzalezSegarra

# Implementation

- [x] The init that normally autogenerates the STM32CubeIDE has been implemented in a simple and concise way. Encoder does not need any configuration.

#  Testing

- [] The same tests that were passed when the service was implemented have been passed.

2022-12-10 09:02 UTC, PabloGonzalezSegarra commented
Estoy teniendo algunos problemillas inesperados con el testeo del encoder. El lunes espero tenerlos arreglados.

2022-12-10 12:23 UTC, StefanCostea requested changes

2022-12-10 12:23 UTC, StefanCostea commented on Src/HALAL/Services/Encoder/Encoder.cpp
> +	  /* USER CODE BEGIN TIM3_Init 1 */
cabron si lo vas a copiar de la hal quita los comments xdd

2022-12-12 14:53 UTC, ricardochust commented on Src/HALAL/Services/Encoder/Encoder.cpp
>  	timer->Instance->CNT = 0;
cambia el reset de 0 a 32768

2022-12-12 15:36 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Encoder/Encoder.cpp
>  	timer->Instance->CNT = 0;
cierto

2022-12-12 15:37 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Encoder/Encoder.cpp
> +	  /* USER CODE BEGIN TIM3_Init 1 */
xD

2022-12-12 19:33 UTC, alejandrogonzalvo requested changes
Refactoriza el init y utiliza timerperipheral, queda mas limpio que usar un par y hace que la libreria sea mas coherente

2022-12-12 19:33 UTC, alejandrogonzalvo commented on Inc/HALAL/Services/Encoder/Encoder.hpp
> +	static map<pair<Pin, Pin>, pair<TIM_HandleTypeDef*, TIM_TypeDef*>> pin_timer_map;
Ahora que ya está mergeado, podrias usar el TimerPeripheral, quedaria mucho mas limpio
```suggestion
	static map<pair<Pin, Pin>, TimerPeripheral> pin_timer_map;
```

2022-12-12 19:33 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Encoder/Encoder.cpp
> +	);
```suggestion
	for (pair<uint8_t, pair<Pin, Pin>> instance : registered_encoder) {
		init(Encoder::pin_timer_map[instance.second]);
	);
```

2022-12-12 19:33 UTC, alejandrogonzalvo commented on Src/HALAL/Services/Encoder/Encoder.cpp
> +	  encoder.first->Init.Period = 65535;
```suggestion
	  encoder.first->Instance = encoder.second;
	  encoder.first->Init.Prescaler = timer.prescaler;
	  encoder.first->Init.CounterMode = TIM_COUNTERMODE_UP;
	  encoder.first->Init.Period = timer.period;
```
Si utilizaras timer_peripheral puedes configurar el timer en el runes y luego aqui indicar la configuracion.

2022-12-13 14:20 UTC, PabloGonzalezSegarra commented on Src/HALAL/Services/Encoder/Encoder.cpp
> +	  encoder.first->Init.Period = 65535;
Eso es constante.

2022-12-14 16:57 UTC, alejandrogonzalvo approved these changes

2022-12-14 17:04 UTC, merged