Added extra features to Packets
HyperloopUPV-H8/ST-LIB pull request #86
Opened 2022-12-11 23:33 UTC by StefanCostea

This PR adds certain functionalities to Packet and PacketValue classes:
·Now Custom types can be sent and received with packets
·Now Dynamic Container Types can be sent and received with packets

>**Note**
>The sender can update the size of dynamic containers when building again a Packet but when receiving them the size received must be the same one as the last size sent, a way to bypass this is having all dynamic containers have a label before them indicating the size of the container, this is yet not implemented and will be further done if needed

Sintax for Packet Creation now looks like this:
![image](https://user-images.githubusercontent.com/24866863/206935502-100d6564-f758-4eac-add1-bd007040fce2.png)

2022-12-12 00:59 UTC, StefanCostea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Packets upgrade](https://trello.com/c/N3enJuvV/64-packets-upgrade)

2022-12-12 09:09 UTC, alejandrogonzalvo requested changes
Mejorar legibilidad en algunas partes y implementacion en cpp a parte.
Que tests ha pasado?

2022-12-12 09:09 UTC, alejandrogonzalvo commented on Inc/HALAL/Models/Packets/PacketValue.hpp
> +        typename C::const_iterator(C::*)() const>::value, void>::type*))[1];
Esto que hace? Ha de haber alguna forma de hacerlo mas legible

2022-12-12 09:09 UTC, alejandrogonzalvo commented on Inc/HALAL/Models/Packets/PacketValue.hpp
> +    }
Implementacion en un cpp a parte

2022-12-12 13:21 UTC, StefanCostea commented on Inc/HALAL/Models/Packets/PacketValue.hpp
> +    }
Las clases de template no se pueden separar en cpp

2022-12-12 13:22 UTC, StefanCostea commented on Inc/HALAL/Models/Packets/PacketValue.hpp
> +    }
El linker explota

2022-12-12 13:22 UTC, StefanCostea commented
Ahora adjunto tests

2022-12-12 13:29 UTC, StefanCostea commented on Inc/HALAL/Models/Packets/PacketValue.hpp
> +    }
De hecho si uso los conceptos ni si quiera puedo sacar la implementación de la declaración de la clase

2022-12-13 07:43 UTC, alejandrogonzalvo approved these changes

2022-12-13 15:48 UTC, ricardochust commented on Inc/ST-LIB.hpp
> +//#include "Communication/UART/UART.hpp"
uncomment this include

2022-12-13 16:50 UTC, ricardochust approved these changes

2022-12-13 16:51 UTC, merged