Features/dma init
HyperloopUPV-H8/ST-LIB pull request #87
Opened 2022-12-12 17:53 UTC by alejandrogonzalvo

# DMA Peripheral

## Usage:
```cpp
  DMA::inscribe_stream(DMA::Stream::DMA1Stream0);
  DMA::start();
```

## Implementation:
```cpp
void DMA::start() {
	  __HAL_RCC_DMA1_CLK_ENABLE();
	for (Stream dma_stream : inscribed_streams) {
		HAL_NVIC_SetPriority( (IRQn_Type)dma_stream, 0, 0);
		HAL_NVIC_EnableIRQ( (IRQn_Type)dma_stream);
	}
}
```

## Testing:
I replaced `MX_DMA_Init()` with `DMA::start()` on ADC TestCases and it kept working.

2022-12-14 19:51 UTC, PabloGonzalezSegarra requested changes
Hasta que no se pasen tests más serios no se puede aprovar !!!!

2022-12-22 09:54 UTC, PabloGonzalezSegarra approved these changes

2022-12-22 09:55 UTC, PabloGonzalezSegarra commented
Te lo apruebo y lo testearemos mientras validamos la ST-LIB.

2023-01-05 13:21 UTC, ricardochust approved these changes

2023-01-05 17:10 UTC, StefanCostea approved these changes

2023-01-05 19:09 UTC, merged